"""
Depression_gripper_generation_v2.py

Run order:
    Depression_Completion.py
        -> repairModel_mesh.py
        -> Depression_gripper_generation_v2.py
        -> Depression_model_orient_bbox.py

Purpose:
    Add a one-piece PLA gripper onto the depression repair model top plane.
    Compared with the previous version, the twist-off neck is no longer a tiny
    cuboid. It is a continuous V / dog-bone transition section connecting the
    lower base block and the upper grip body.

Inputs expected in COMPLETION_DIR:
    model.stl      : generated by repairModel_mesh.py
    meta.npz       : generated by Depression_Completion.py, should contain:
                    - n_axis
                    - repair_top_center or top_plane_center
                    - side_n_mark, or u_axis/v_axis

Outputs:
    model_with_gripper.stl
    gripper_only.stl
    gripper_meta.npz

Geometry definition:
    - attach center   : repair_top_center if available, otherwise top_plane_center
    - height direction: -n_axis, i.e. outward normal of top plane
    - length direction: v_axis
    - width direction : u_axis
    - twist-off V-neck starts 2 mm above model top surface
    - no round / chamfer / fillet operation

Important unit setting:
    If current STL/PCD/meta are in meters, keep MM = 0.001.
    If current STL/PCD/meta are already in millimeters, set MM = 1.0.
"""

import os
import numpy as np
import open3d as o3d


# =========================================================
# User config
# =========================================================
COMPLETION_DIR = r"E:\HKUSTGZ\AAM\construction\data\completion_result\depression"
INPUT_STL = os.path.join(COMPLETION_DIR, "model.stl")
META_PATH = os.path.join(COMPLETION_DIR, "meta.npz")
OUTPUT_STL = os.path.join(COMPLETION_DIR, "model_with_gripper.stl")
GRIPPER_ONLY_STL = os.path.join(COMPLETION_DIR, "gripper_only.stl")
GRIPPER_META = os.path.join(COMPLETION_DIR, "gripper_meta.npz")

# Unit conversion: millimeter -> current model unit.
MM = 0.001

# Small overlap into the model to avoid numerical gap at top surface.

##  base section: 6 × 9 mm
##        ↓ 线性收缩
##  waist section: 3 × 5 mm
##        ↓ 线性放大
##  grip section: 8 × 12 mm

## u,v参数要按比例调整 6:9 = 4:6 这样

EMBED_DEPTH = 0.0 * MM

BASE_HEIGHT = 2.0 * MM
BASE_WIDTH_U = 6.0 * MM
BASE_LENGTH_V = 9.0 * MM

V_NECK_HEIGHT = 3.0 * MM
V_NECK_MIN_WIDTH_U = 2 * MM
V_NECK_MIN_LENGTH_V = 3 * MM
V_NECK_SECTION_NUM = 15

GRIP_BODY_HEIGHT = 15.0 * MM
GRIP_BODY_WIDTH_U = 6.0 * MM
GRIP_BODY_LENGTH_V = 9.0 * MM

VISUALIZE = True

# =========================================================
# Basic utils
# =========================================================
def normalize(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=float).reshape(3)
    n = np.linalg.norm(v)
    if n < 1e-12:
        raise ValueError(f"zero-length vector: {v}")
    return v / n


def unwrap_np_value(x):
    if isinstance(x, np.ndarray):
        if x.shape == ():
            return x.item()
        return x
    return x


def load_meta(meta_path: str):
    if not os.path.exists(meta_path):
        raise FileNotFoundError(f"Cannot find meta.npz: {meta_path}")

    data = np.load(meta_path, allow_pickle=True)

    if "n_axis" not in data.files:
        raise KeyError("meta.npz must contain n_axis")

    meta = {k: unwrap_np_value(data[k]) for k in data.files}
    meta["n_axis"] = normalize(np.asarray(meta["n_axis"], dtype=float))


    if "top_plane_center" in meta:
        top_plane_center = np.asarray(meta["top_plane_center"], dtype=float).reshape(3)
        #attach_key = "top_plane_center"
    if 'repair_point_center' in meta:
        repair_point_center = meta['repair_point_center']

    # 这里有一个潜在的问题，attach center有可能因为缺陷模型的极端畸形而周围没有点云，是在半空的
    attach_center = np.asarray([repair_point_center[0], repair_point_center[1],top_plane_center[2] ])

    meta["attach_center"] = attach_center
    #meta["attach_center_key"] = attach_key
    return meta


def recover_uv_axes(meta: dict):
    """
    Recover u_axis and v_axis.

    Best case:
        meta.npz already contains u_axis and v_axis.

    Current Depression_Completion.py case:
        side_n_mark is saved. For CORNER_MODE = max_u_max_v, current code stores:
            side_n_mark['max_u_outward'] = v_axis
            side_n_mark['max_v_outward'] = u_axis
    """
    n_axis = normalize(meta["n_axis"])

    if "u_axis" in meta and "v_axis" in meta:
        u_axis = normalize(np.asarray(meta["u_axis"], dtype=float))
        v_axis = normalize(np.asarray(meta["v_axis"], dtype=float))
        return u_axis, v_axis

    if "side_n_mark" not in meta:
        raise KeyError("meta.npz must contain either u_axis/v_axis or side_n_mark")

    side_n_mark = meta["side_n_mark"]
    if not isinstance(side_n_mark, dict):
        raise TypeError(f"side_n_mark should be dict, got {type(side_n_mark)}")

    if "max_v_outward" in side_n_mark:
        u_axis = normalize(np.asarray(side_n_mark["max_v_outward"], dtype=float))
    elif "min_v_outward" in side_n_mark:
        u_axis = normalize(np.asarray(side_n_mark["min_v_outward"], dtype=float))
    else:
        raise KeyError("Cannot recover u_axis from side_n_mark. Need max_v_outward or min_v_outward.")

    if "max_u_outward" in side_n_mark:
        v_axis = normalize(np.asarray(side_n_mark["max_u_outward"], dtype=float))
    elif "min_u_outward" in side_n_mark:
        v_axis = normalize(np.asarray(side_n_mark["min_u_outward"], dtype=float))
    else:
        v_axis = normalize(np.cross(n_axis, u_axis))

    # Re-orthogonalize.
    u_axis = normalize(u_axis - np.dot(u_axis, n_axis) * n_axis)
    v_axis = normalize(v_axis - np.dot(v_axis, n_axis) * n_axis - np.dot(v_axis, u_axis) * u_axis)

    if np.dot(np.cross(u_axis, v_axis), n_axis) < 0:
        v_axis = -v_axis

    return u_axis, v_axis


# =========================================================
# Mesh construction
# =========================================================
def make_oriented_box_from_s_range(
    surface_center: np.ndarray,
    u_axis: np.ndarray,
    v_axis: np.ndarray,
    h_axis: np.ndarray,
    size_u: float,
    size_v: float,
    s0: float,
    s1: float,
):
    """
    Create an oriented rectangular box.

    h_axis is the gripper height direction, here h_axis = -n_axis.
    s = 0 is the top plane surface.
    """
    surface_center = np.asarray(surface_center, dtype=float).reshape(3)
    u_axis = normalize(u_axis)
    v_axis = normalize(v_axis)
    h_axis = normalize(h_axis)

    if s1 <= s0:
        raise ValueError("s1 must be larger than s0")

    center_s = 0.5 * (s0 + s1)
    size_h = s1 - s0
    center = surface_center + center_s * h_axis

    hu = 0.5 * size_u
    hv = 0.5 * size_v
    hh = 0.5 * size_h

    verts = []
    for sh in [-hh, hh]:
        for su, sv in [(-hu, -hv), (hu, -hv), (hu, hv), (-hu, hv)]:
            verts.append(center + su * u_axis + sv * v_axis + sh * h_axis)
    verts = np.asarray(verts)

    faces = np.array([
        [0, 2, 1], [0, 3, 2],      # bottom
        [4, 5, 6], [4, 6, 7],      # top
        [0, 1, 5], [0, 5, 4],      # side
        [1, 2, 6], [1, 6, 5],      # side
        [2, 3, 7], [2, 7, 6],      # side
        [3, 0, 4], [3, 4, 7],      # side
    ], dtype=np.int32)

    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    mesh.triangles = o3d.utility.Vector3iVector(faces)
    mesh.compute_vertex_normals()
    return mesh


def make_variable_section_box(
    surface_center: np.ndarray,
    u_axis: np.ndarray,
    v_axis: np.ndarray,
    h_axis: np.ndarray,
    sections: list,
):
    """
    Create a continuous oriented prism with variable rectangular section.

    sections:
        list of (s, size_u, size_v), sorted along h_axis.
        Each section is a rectangle centered at surface_center + s * h_axis.

    This is used to create the V / dog-bone twist-off neck.
    The neck is continuous: no isolated small cuboid is inserted.
    """
    surface_center = np.asarray(surface_center, dtype=float).reshape(3)
    u_axis = normalize(u_axis)
    v_axis = normalize(v_axis)
    h_axis = normalize(h_axis)

    if len(sections) < 2:
        raise ValueError("Need at least two sections")

    sections = sorted(sections, key=lambda x: x[0])

    verts = []
    for s, size_u, size_v in sections:
        hu = 0.5 * float(size_u)
        hv = 0.5 * float(size_v)
        center = surface_center + float(s) * h_axis
        for su, sv in [(-hu, -hv), (hu, -hv), (hu, hv), (-hu, hv)]:
            verts.append(center + su * u_axis + sv * v_axis)
    verts = np.asarray(verts)

    faces = []

    # Bottom cap
    faces += [[0, 2, 1], [0, 3, 2]]

    # Side faces between adjacent sections
    for i in range(len(sections) - 1):
        a = 4 * i
        b = 4 * (i + 1)
        # Four side quads, each split into two triangles
        faces += [
            [a + 0, a + 1, b + 1], [a + 0, b + 1, b + 0],
            [a + 1, a + 2, b + 2], [a + 1, b + 2, b + 1],
            [a + 2, a + 3, b + 3], [a + 2, b + 3, b + 2],
            [a + 3, a + 0, b + 0], [a + 3, b + 0, b + 3],
        ]

    # Top cap
    t = 4 * (len(sections) - 1)
    faces += [[t + 0, t + 1, t + 2], [t + 0, t + 2, t + 3]]

    mesh = o3d.geometry.TriangleMesh()
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    mesh.triangles = o3d.utility.Vector3iVector(np.asarray(faces, dtype=np.int32))
    mesh.remove_duplicated_vertices()
    mesh.remove_duplicated_triangles()
    mesh.remove_degenerate_triangles()
    mesh.remove_unreferenced_vertices()
    mesh.compute_vertex_normals()
    return mesh


def build_v_neck_sections(s0, s1):
    """
    Build V-neck sections.

    The size profile is:
        bottom: same as base block
        middle: narrow waist
        top   : same as grip body

    This produces V-shaped grooves on both sides and connects base -> grip smoothly.
    """
    if V_NECK_SECTION_NUM < 3:
        n_sec = 3
    else:
        n_sec = int(V_NECK_SECTION_NUM)
    if n_sec % 2 == 0:
        n_sec += 1

    sections = []
    for i in range(n_sec):
        t = i / (n_sec - 1)
        s = s0 + t * (s1 - s0)

        if t <= 0.5:
            # base -> waist
            a = t / 0.5
            size_u = (1 - a) * BASE_WIDTH_U + a * V_NECK_MIN_WIDTH_U
            size_v = (1 - a) * BASE_LENGTH_V + a * V_NECK_MIN_LENGTH_V
        else:
            # waist -> grip body
            a = (t - 0.5) / 0.5
            size_u = (1 - a) * V_NECK_MIN_WIDTH_U + a * GRIP_BODY_WIDTH_U
            size_v = (1 - a) * V_NECK_MIN_LENGTH_V + a * GRIP_BODY_LENGTH_V

        sections.append((s, size_u, size_v))

    return sections


def merge_meshes(meshes):
    merged = o3d.geometry.TriangleMesh()
    for m in meshes:
        merged += m
    merged.remove_duplicated_vertices()
    merged.remove_duplicated_triangles()
    merged.remove_degenerate_triangles()
    merged.remove_unreferenced_vertices()
    merged.compute_vertex_normals()
    return merged


# =========================================================
# Main
# =========================================================
def main():
    meta = load_meta(META_PATH)

    n_axis = normalize(meta["n_axis"])
    h_axis = -n_axis
    attach_center = meta["attach_center"]
    u_axis, v_axis = recover_uv_axes(meta)

    if not os.path.exists(INPUT_STL):
        raise FileNotFoundError(f"Cannot find input STL from repairModel_mesh.py: {INPUT_STL}")

    model_mesh = o3d.io.read_triangle_mesh(INPUT_STL)
    if len(model_mesh.vertices) == 0:
        raise RuntimeError(f"Empty mesh: {INPUT_STL}")
    model_mesh.compute_vertex_normals()

    # 1) Lower base block: top surface -> 2 mm above top surface.
    base_block = make_oriented_box_from_s_range(
        surface_center=attach_center,
        u_axis=u_axis,
        v_axis=v_axis,
        h_axis=h_axis,
        size_u=BASE_WIDTH_U,
        size_v=BASE_LENGTH_V,
        s0=-EMBED_DEPTH,
        s1=BASE_HEIGHT,
    )

    # 2) Continuous V / dog-bone neck: starts 2 mm above top surface.
    vneck_s0 = BASE_HEIGHT
    vneck_s1 = BASE_HEIGHT + V_NECK_HEIGHT
    vneck_sections = build_v_neck_sections(vneck_s0, vneck_s1)
    v_neck = make_variable_section_box(
        surface_center=attach_center,
        u_axis=u_axis,
        v_axis=v_axis,
        h_axis=h_axis,
        sections=vneck_sections,
    )

    # 3) Upper grip body.
    grip_body = make_oriented_box_from_s_range(
        surface_center=attach_center,
        u_axis=u_axis,
        v_axis=v_axis,
        h_axis=h_axis,
        size_u=GRIP_BODY_WIDTH_U,
        size_v=GRIP_BODY_LENGTH_V,
        s0=vneck_s1,
        s1=vneck_s1 + GRIP_BODY_HEIGHT,
    )

    gripper_mesh = merge_meshes([base_block, v_neck, grip_body])
    full_mesh = merge_meshes([model_mesh, gripper_mesh])

    os.makedirs(COMPLETION_DIR, exist_ok=True)
    ok1 = o3d.io.write_triangle_mesh(GRIPPER_ONLY_STL, gripper_mesh)
    ok2 = o3d.io.write_triangle_mesh(OUTPUT_STL, full_mesh)
    if not ok1:
        raise RuntimeError(f"Failed to write {GRIPPER_ONLY_STL}")
    if not ok2:
        raise RuntimeError(f"Failed to write {OUTPUT_STL}")

    np.savez(
        GRIPPER_META,
        attach_center=attach_center,
        #attach_center_key=meta["attach_center_key"],
        n_axis=n_axis,
        h_axis=h_axis,
        u_axis=u_axis,
        v_axis=v_axis,
        mm=float(MM),
        embed_depth=float(EMBED_DEPTH),
        base_height=float(BASE_HEIGHT),
        base_width_u=float(BASE_WIDTH_U),
        base_length_v=float(BASE_LENGTH_V),
        v_neck_start_height=float(vneck_s0),
        v_neck_height=float(V_NECK_HEIGHT),
        v_neck_min_width_u=float(V_NECK_MIN_WIDTH_U),
        v_neck_min_length_v=float(V_NECK_MIN_LENGTH_V),
        v_neck_section_num=int(V_NECK_SECTION_NUM),
        grip_body_height=float(GRIP_BODY_HEIGHT),
        grip_body_width_u=float(GRIP_BODY_WIDTH_U),
        grip_body_length_v=float(GRIP_BODY_LENGTH_V),
        output_stl=OUTPUT_STL,
        gripper_only_stl=GRIPPER_ONLY_STL,
    )

    print("\n========== Depression gripper generation v2 done ==========")
    print("input model STL:", INPUT_STL)
    print("output STL:", OUTPUT_STL)
    print("gripper only STL:", GRIPPER_ONLY_STL)
    print("gripper meta:", GRIPPER_META)
    #print("attach center key:", meta["attach_center_key"])
    print("attach center:", attach_center)
    print("height direction h_axis = -n_axis:", h_axis)
    print("width direction u_axis:", u_axis)
    print("length direction v_axis:", v_axis)
    print("V-neck starts at:", vneck_s0, "model unit")
    print("V-neck ends at:", vneck_s1, "model unit")
    print("V-neck waist size [u, v]:", V_NECK_MIN_WIDTH_U, V_NECK_MIN_LENGTH_V)

    if VISUALIZE:
        model_show = o3d.geometry.TriangleMesh(model_mesh)
        base_show = o3d.geometry.TriangleMesh(base_block)
        neck_show = o3d.geometry.TriangleMesh(v_neck)
        grip_show = o3d.geometry.TriangleMesh(grip_body)

        model_show.paint_uniform_color([0.65, 0.65, 0.65])
        base_show.paint_uniform_color([0.65, 0.65, 0.65])
        neck_show.paint_uniform_color([0.65, 0.65, 0.65])
        grip_show.paint_uniform_color([0.65, 0.65, 0.65])

        frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.06)
        o3d.visualization.draw_geometries(
            [model_show, base_show, neck_show, grip_show, frame]
        )


if __name__ == "__main__":
    main()
