"""
hole_grip.py

Purpose
-------
Generate a new hole-repair gripper from scratch, without applying any model
frame/orientation transform in this file.

Design requirement
------------------
1. Read the existing hole repair model and metadata:
       model.stl
       meta.npz
       mark.json
       defect_pcd1.pcd / defect_pcd2.pcd
2. Use trimesh to process meshes.
3. Generate the grip with rectangular loft sections, similar to the depression
   gripper loft idea.
4. The grip grows from the side defect plane, but its growth direction is
       h_axis = -side_n
   where side_n is the inward normal stored in meta.npz.
5. The two neck-to-repair connection points are located on the side-bottom edge,
   i.e. the intersection line between top plane and side plane. The two points
   are placed at edge_mid +/- LINK_PAIR_OFFSET along the edge direction.
6. Grip shape:
       two breakaway necks -> wide low base -> grasp cube.
7. This script does NOT rotate or re-orient the model. It keeps the original
   coordinate frame unchanged.
8. All geometry parameters and computed frame data are saved to gripper_meta.npz
   for later synchronized model/grip rotation.

Assumptions
-----------
- model.stl and point clouds are in meters, as generated by Hole_Completion.py
  and repairModel_mesh.py.
- Design parameters are written in millimeters and multiplied by MM = 0.001.
- meta.npz stores n1/n2 as inward normals.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import open3d as o3d
import trimesh


# =========================================================
# User config
# =========================================================
COMPLETION_DIR = Path(r"E:\HKUSTGZ\AAM\construction\data\completion_result\hole")
INPUT_STL = COMPLETION_DIR / "model.stl"
META_PATH = COMPLETION_DIR / "meta.npz"
MARK_PATH = COMPLETION_DIR / "mark.json"
DEFECT_PCD1 = COMPLETION_DIR / "defect_pcd1.pcd"
DEFECT_PCD2 = COMPLETION_DIR / "defect_pcd2.pcd"

OUTPUT_STL = COMPLETION_DIR / "model_with_gripper.stl"
GRIPPER_ONLY_STL = COMPLETION_DIR / "gripper_only.stl"
GRIPPER_META = COMPLETION_DIR / "gripper_meta.npz"

# Unit conversion: millimeter -> current model unit. Current model unit is meter.
MM = 0.001

# ---------- connection / placement ----------
# Two neck roots are placed at edge_mid +/- LINK_PAIR_OFFSET along top-side edge.
LINK_PAIR_OFFSET = 5.0 * MM

# When extracting the top-side edge center from side defect point cloud, select
# side defect points whose distance to top plane is within this band.
EDGE_BAND = 1.5 * MM

# Small overlap into the repair model to avoid numerical gaps.
EMBED_DEPTH = 0.8 * MM

# ---------- wide low base ----------
BASE_LENGTH_X = 40.0 * MM
BASE_WIDTH_Y = 15.0 * MM
BASE_THICKNESS_Z = 2.0 * MM
BASE_OVERLAP_WITH_NECK = 0.5 * MM

# ---------- neck geometry ----------
NECK_LENGTH = 2.0 * MM
NECK_WIDTH_Y = 2.0 * MM

# neck 厚度强制等于 base 厚度，保证 neck 底部与 base 底部平齐
NECK_THICKNESS_Z = BASE_THICKNESS_Z

# V-notch / weak section. The notch weakens the neck in left-right direction,
# i.e. along local y / edge direction.
FRACTURE_DISTANCE = 1.0 * MM
NOTCH_LENGTH = 0.8 * MM
NOTCH_WIDTH_RATIO = 0.55

# ---------- grasp cube on top of base ----------
GRASP_CUBE_LENGTH_X = 15.0 * MM
GRASP_CUBE_WIDTH_Y = 5.0 * MM
GRASP_CUBE_HEIGHT_Z = 20.0 * MM
GRASP_CUBE_CENTER_X_RATIO = 0.55   # position along base length, 0~1

# ---------- export / merge ----------
BOOLEAN_UNION_GRIP_PARTS = True
BOOLEAN_UNION_WITH_MODEL = False
VISUALIZE = True


# =========================================================
# Basic utilities
# =========================================================
def normalize(v: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    v = np.asarray(v, dtype=float).reshape(3)
    n = np.linalg.norm(v)
    if n < eps:
        raise ValueError(f"zero-length vector: {v}")
    return v / n


def load_trimesh_mesh(path: Path) -> trimesh.Trimesh:
    obj = trimesh.load(str(path), force="mesh", process=True)
    if isinstance(obj, trimesh.Scene):
        meshes = [g for g in obj.geometry.values() if isinstance(g, trimesh.Trimesh)]
        if not meshes:
            raise RuntimeError(f"No mesh found in scene: {path}")
        mesh = trimesh.util.concatenate(meshes)
    else:
        mesh = obj

    if mesh.vertices.shape[0] == 0 or mesh.faces.shape[0] == 0:
        raise RuntimeError(f"Empty mesh: {path}")

    #mesh.remove_duplicate_faces()
    #mesh.remove_degenerate_faces()
    mesh.remove_unreferenced_vertices()
    mesh.fix_normals()
    return mesh


def normalize_plane(plane_model: np.ndarray) -> np.ndarray:
    """
    plane_model = [a, b, c, d], ax + by + cz + d = 0.
    Return [n_unit, d_scaled].
    """
    p = np.asarray(plane_model, dtype=float).reshape(4)
    n = p[:3]
    d = float(p[3])
    s = np.linalg.norm(n)
    if s < 1e-12:
        raise ValueError("invalid plane normal")
    return np.r_[n / s, d / s]


def orient_plane_to_normal(plane_model: np.ndarray, target_normal: np.ndarray) -> np.ndarray:
    """Orient plane normal to target_normal."""
    p = normalize_plane(plane_model)
    target_normal = normalize(target_normal)
    if np.dot(p[:3], target_normal) < 0:
        p = -p
    return p


def load_meta_and_mark(meta_path: Path, mark_path: Path) -> Tuple[Dict[str, np.ndarray], Dict[str, str]]:
    if not meta_path.exists():
        raise FileNotFoundError(f"Cannot find meta file: {meta_path}")
    if not mark_path.exists():
        raise FileNotFoundError(f"Cannot find mark file: {mark_path}")

    raw = np.load(str(meta_path), allow_pickle=True)
    meta = {k: raw[k] for k in raw.files}

    with open(str(mark_path), "r", encoding="utf-8") as f:
        mark = json.load(f)

    required = [
        "plane1_model", "plane2_model", "n1", "n2",
        "defect1_center", "defect2_center",
        "object_center",
    ]
    for k in required:
        if k not in meta:
            raise KeyError(f"meta.npz does not contain required key: {k}")

    return meta, mark


def get_top_side_ids(mark: Dict[str, str]) -> Tuple[int, int]:
    if mark.get("top") == "defect_pcd1":
        top_id = 1
    elif mark.get("top") == "defect_pcd2":
        top_id = 2
    else:
        raise ValueError(f"Unknown mark['top']: {mark.get('top')}")

    if mark.get("side") == "defect_pcd1":
        side_id = 1
    elif mark.get("side") == "defect_pcd2":
        side_id = 2
    else:
        raise ValueError(f"Unknown mark['side']: {mark.get('side')}")

    if top_id == side_id:
        raise ValueError(f"top and side should be different, got {mark}")

    return top_id, side_id


# =========================================================
# Edge / local frame construction
# =========================================================
def plane_intersection_line(plane_a: np.ndarray, plane_b: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    """
    Return one point p0 and unit direction d of two plane intersection line.
    Planes should be normalized [nx, ny, nz, d].
    """
    p1 = normalize_plane(plane_a)
    p2 = normalize_plane(plane_b)
    n1, d1 = p1[:3], p1[3]
    n2, d2 = p2[:3], p2[3]

    line_dir = np.cross(n1, n2)
    line_dir = normalize(line_dir)

    # Solve:
    # n1 · p = -d1
    # n2 · p = -d2
    # line_dir · p = 0
    A = np.vstack([n1, n2, line_dir])
    b = np.array([-d1, -d2, 0.0], dtype=float)
    p0 = np.linalg.solve(A, b)
    return p0, line_dir


def read_pcd_points(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Cannot find point cloud: {path}")
    pcd = o3d.io.read_point_cloud(str(path))
    pts = np.asarray(pcd.points, dtype=float)
    if pts.shape[0] == 0:
        raise RuntimeError(f"Empty point cloud: {path}")
    return pts


def estimate_edge_midpoint_from_side_pcd(
    side_pts: np.ndarray,
    top_plane: np.ndarray,
    side_plane: np.ndarray,
    edge_band: float,
) -> Tuple[np.ndarray, np.ndarray, Dict[str, float]]:
    """
    Find the midpoint of the top-side intersection edge using side defect points.

    1. Compute exact top-side plane intersection line.
    2. Select side defect points close to the top plane.
    3. Project those selected points onto the line and take median coordinate.
    4. Return edge_mid on the exact line.
    """
    top_plane = normalize_plane(top_plane)
    side_plane = normalize_plane(side_plane)
    p0, edge_axis = plane_intersection_line(top_plane, side_plane)

    n_top, d_top = top_plane[:3], top_plane[3]
    dist_to_top = np.abs(side_pts @ n_top + d_top)

    mask = dist_to_top <= edge_band
    selected = side_pts[mask]

    # Fallback: take nearest 20% points if band is too strict.
    if selected.shape[0] < 5:
        k = max(5, int(0.20 * side_pts.shape[0]))
        idx = np.argsort(dist_to_top)[:k]
        selected = side_pts[idx]

    t = (selected - p0) @ edge_axis
    t_mid = float(np.median(t))
    edge_mid = p0 + t_mid * edge_axis

    info = {
        "selected_edge_points": int(selected.shape[0]),
        "edge_band": float(edge_band),
        "t_min": float(np.min(t)),
        "t_max": float(np.max(t)),
        "t_mid": float(t_mid),
    }
    return edge_mid, edge_axis, info


def build_grip_frame(
    top_n_inward: np.ndarray,
    side_n_inward: np.ndarray,
    edge_axis_hint: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Local grip frame:
        x_axis = h_axis = -top_n_inward, grip growth direction.
        y_axis = top-side edge direction, used for left/right neck offset.
        z_axis = roughly side outward direction, used for base thickness and cube height.
    """
    x_axis = normalize(-side_n_inward)
    #y_axis = normalize(edge_axis_hint)
    z_axis = normalize(top_n_inward)
    y_axis = np.cross(z_axis, x_axis)
    # Make y exactly perpendicular to x.
    #y_axis = y_axis - np.dot(y_axis, x_axis) * x_axis
    #y_axis = normalize(y_axis)
#
    #z_axis = normalize(np.cross(x_axis, y_axis))
#
    ## Prefer z_axis to point toward side inward direction.
    #side_outward = normalize(side_n_inward)
    #if np.dot(z_axis, side_outward) < 0:
    #    y_axis = -y_axis
    #    z_axis = normalize(np.cross(x_axis, y_axis))

    return x_axis, y_axis, z_axis


def make_frame_matrix(origin: np.ndarray, x_axis: np.ndarray, y_axis: np.ndarray, z_axis: np.ndarray) -> np.ndarray:
    T = np.eye(4)
    T[:3, 0] = normalize(x_axis)
    T[:3, 1] = normalize(y_axis)
    T[:3, 2] = normalize(z_axis)
    T[:3, 3] = np.asarray(origin, dtype=float).reshape(3)
    return T


# =========================================================
# Loft / mesh construction in local frame
# =========================================================
def create_offset_rectangular_loft_local(sections: List[Tuple[float, float, float, float, float]]) -> trimesh.Trimesh:
    """
    Create a rectangular loft mesh in local coordinates.

    sections = [(x, y_center, z_center, width_y, thickness_z), ...]

    Only the first and last sections are capped. Adjacent sections are connected
    directly, avoiding internal caps.
    """
    if len(sections) < 2:
        raise ValueError("Need at least two sections")

    sections = sorted(sections, key=lambda s: s[0])

    vertices = []
    faces = []

    for x, yc, zc, wy, tz in sections:
        vertices.extend([
            [x, yc - wy / 2.0, zc - tz / 2.0],
            [x, yc + wy / 2.0, zc - tz / 2.0],
            [x, yc + wy / 2.0, zc + tz / 2.0],
            [x, yc - wy / 2.0, zc + tz / 2.0],
        ])

    for i in range(len(sections) - 1):
        a = 4 * i
        b = 4 * (i + 1)
        quads = [
            [a + 0, a + 1, b + 1, b + 0],
            [a + 1, a + 2, b + 2, b + 1],
            [a + 2, a + 3, b + 3, b + 2],
            [a + 3, a + 0, b + 0, b + 3],
        ]
        for q in quads:
            faces.append([q[0], q[1], q[2]])
            faces.append([q[0], q[2], q[3]])

    # start cap
    faces.append([0, 2, 1])
    faces.append([0, 3, 2])

    # end cap
    last = 4 * (len(sections) - 1)
    faces.append([last + 0, last + 1, last + 2])
    faces.append([last + 0, last + 2, last + 3])

    mesh = trimesh.Trimesh(
        vertices=np.asarray(vertices, dtype=float),
        faces=np.asarray(faces, dtype=np.int64),
        process=True,
    )
    mesh.remove_unreferenced_vertices()
    mesh.fix_normals()
    return mesh


def create_box_local(center: Tuple[float, float, float], extents: Tuple[float, float, float]) -> trimesh.Trimesh:
    mesh = trimesh.creation.box(extents=np.asarray(extents, dtype=float))
    mesh.apply_translation(np.asarray(center, dtype=float))
    mesh.remove_unreferenced_vertices()
    mesh.fix_normals()
    return mesh


def create_breakaway_neck_local(
    y_offset: float,
    root_z: float,
    end_z: float,
) -> Tuple[trimesh.Trimesh, np.ndarray]:
    """
    Create one neck from side-top edge to wide base.
    The V notch reduces width along local y direction.
    """
    if FRACTURE_DISTANCE <= 0.25 * MM:
        raise ValueError("FRACTURE_DISTANCE too small")
    if FRACTURE_DISTANCE >= NECK_LENGTH:
        raise ValueError("FRACTURE_DISTANCE must be smaller than NECK_LENGTH")

    x0 = -EMBED_DEPTH
    x1 = 0.0
    x2 = max(FRACTURE_DISTANCE - NOTCH_LENGTH / 2.0, 0.05 * MM)
    x3 = FRACTURE_DISTANCE
    x4 = min(FRACTURE_DISTANCE + NOTCH_LENGTH / 2.0, NECK_LENGTH - 0.05 * MM)
    x5 = NECK_LENGTH

    def z_at(x: float) -> float:
        a = np.clip((x - x1) / max(x5 - x1, 1e-12), 0.0, 1.0)
        return (1.0 - a) * root_z + a * end_z

    waist_width = NECK_WIDTH_Y * NOTCH_WIDTH_RATIO
    sections = [
        (x0, y_offset, root_z, NECK_WIDTH_Y, NECK_THICKNESS_Z),
        (x1, y_offset, root_z, NECK_WIDTH_Y, NECK_THICKNESS_Z),
        (x2, y_offset, z_at(x2), NECK_WIDTH_Y, NECK_THICKNESS_Z),
        (x3, y_offset, z_at(x3), waist_width, NECK_THICKNESS_Z),
        (x4, y_offset, z_at(x4), NECK_WIDTH_Y, NECK_THICKNESS_Z),
        (x5, y_offset, end_z, NECK_WIDTH_Y, NECK_THICKNESS_Z),
    ]
    mesh = create_offset_rectangular_loft_local(sections)
    return mesh, np.asarray(sections, dtype=float)


def boolean_union_safe(meshes: List[trimesh.Trimesh], label: str) -> trimesh.Trimesh:
    """Try boolean union, fallback to concatenate."""
    try:
        out = trimesh.boolean.union(meshes, engine="manifold")
        if out is not None and len(out.vertices) > 0:
            #out.remove_duplicate_faces()
            #out.remove_degenerate_faces()
            out.remove_unreferenced_vertices()
            out.fix_normals()
            print(f"[OK] boolean union succeeded: {label}")
            return out
    except Exception as e:
        print(f"[WARN] boolean union failed for {label}: {e}")

    print(f"[WARN] fallback to concatenate: {label}")
    out = trimesh.util.concatenate(meshes)
    out.remove_unreferenced_vertices()
    out.fix_normals()
    return out


def create_grip_local() -> Tuple[trimesh.Trimesh, Dict[str, np.ndarray]]:
    """
    Create the whole local grip:
        two breakaway necks + wide low base + grasp cube.
    """
    base_start_x = NECK_LENGTH - BASE_OVERLAP_WITH_NECK
    base_center_x = base_start_x + BASE_LENGTH_X / 2.0
    base_center_z = BASE_THICKNESS_Z / 2.0

    base = create_box_local(
        center=(base_center_x, 0.0, base_center_z),
        extents=(BASE_LENGTH_X, BASE_WIDTH_Y, BASE_THICKNESS_Z),
    )

    cube_center_x = base_start_x + BASE_LENGTH_X * GRASP_CUBE_CENTER_X_RATIO
    cube_center_z = BASE_THICKNESS_Z + GRASP_CUBE_HEIGHT_Z / 2.0
    cube = create_box_local(
        center=(cube_center_x, 0.0, cube_center_z),
        extents=(GRASP_CUBE_LENGTH_X, GRASP_CUBE_WIDTH_Y, GRASP_CUBE_HEIGHT_Z),
    )

    # Two necks connect to the front edge region of the base.
    root_z = base_center_z
    end_z = base_center_z
    y_offsets = np.array([-LINK_PAIR_OFFSET, LINK_PAIR_OFFSET], dtype=float)

    neck_meshes = []
    neck_sections = []
    for yoff in y_offsets:
        neck, sections = create_breakaway_neck_local(y_offset=float(yoff), root_z=root_z, end_z=end_z)
        neck_meshes.append(neck)
        neck_sections.append(sections)

    parts = [base, cube] + neck_meshes
    if BOOLEAN_UNION_GRIP_PARTS:
        grip = boolean_union_safe(parts, "grip parts")
    else:
        grip = trimesh.util.concatenate(parts)
        grip.remove_unreferenced_vertices()
        grip.fix_normals()

    info = {
        "base_start_x": np.asarray(base_start_x),
        "base_center": np.asarray([base_center_x, 0.0, base_center_z]),
        "cube_center": np.asarray([cube_center_x, 0.0, cube_center_z]),
        "y_offsets": y_offsets,
        "neck_sections_left": neck_sections[0],
        "neck_sections_right": neck_sections[1],
    }
    return grip, info


# =========================================================
# Main generation
# =========================================================
def main():
    meta, mark = load_meta_and_mark(META_PATH, MARK_PATH)
    top_id, side_id = get_top_side_ids(mark)

    top_n = normalize(np.asarray(meta[f"n{top_id}"], dtype=float))
    side_n = normalize(np.asarray(meta[f"n{side_id}"], dtype=float))

    top_plane = orient_plane_to_normal(meta[f"plane{top_id}_model"], top_n)
    side_plane = orient_plane_to_normal(meta[f"plane{side_id}_model"], side_n)

    side_pcd_path = DEFECT_PCD1 if side_id == 1 else DEFECT_PCD2
    side_pts = read_pcd_points(side_pcd_path)

    edge_mid, edge_axis_raw, edge_info = estimate_edge_midpoint_from_side_pcd(
        side_pts=side_pts,
        top_plane=top_plane,
        side_plane=side_plane,
        edge_band=EDGE_BAND,
    )

    h_axis, edge_axis, z_axis = build_grip_frame(
        top_n_inward=top_n,
        side_n_inward=side_n,
        edge_axis_hint=edge_axis_raw,
    )

    T = make_frame_matrix(edge_mid, h_axis, edge_axis, z_axis)

    model_mesh = load_trimesh_mesh(INPUT_STL)
    grip_local, grip_info = create_grip_local()
    grip_world = grip_local.copy()
    grip_world.apply_transform(T)

    if BOOLEAN_UNION_WITH_MODEL:
        full_mesh = boolean_union_safe([model_mesh, grip_world], "model + grip")
    else:
        full_mesh = trimesh.util.concatenate([model_mesh, grip_world])
        full_mesh.remove_unreferenced_vertices()
        full_mesh.fix_normals()

    os.makedirs(str(COMPLETION_DIR), exist_ok=True)
    grip_world.export(str(GRIPPER_ONLY_STL))
    full_mesh.export(str(OUTPUT_STL))

    # Two real root points on the top-side edge in world/model frame.
    root_points = np.vstack([
        edge_mid - LINK_PAIR_OFFSET * edge_axis,
        edge_mid + LINK_PAIR_OFFSET * edge_axis,
    ])

    np.savez(
        str(GRIPPER_META),
        grip_type="hole_big_bottom_from_top_side_edge",
        input_stl=str(INPUT_STL),
        output_stl=str(OUTPUT_STL),
        gripper_only_stl=str(GRIPPER_ONLY_STL),
        meta_path=str(META_PATH),
        mark_path=str(MARK_PATH),
        mm=float(MM),
        top_id=int(top_id),
        side_id=int(side_id),
        top_n_inward=top_n,
        side_n_inward=side_n,
        h_axis_minus_top_n=h_axis,
        edge_axis=edge_axis,
        z_axis=z_axis,
        edge_mid=edge_mid,
        root_points=root_points,
        link_pair_offset=float(LINK_PAIR_OFFSET),
        edge_band=float(EDGE_BAND),
        edge_info=json.dumps(edge_info),
        embed_depth=float(EMBED_DEPTH),
        neck_length=float(NECK_LENGTH),
        neck_width_y=float(NECK_WIDTH_Y),
        neck_thickness_z=float(NECK_THICKNESS_Z),
        fracture_distance=float(FRACTURE_DISTANCE),
        notch_length=float(NOTCH_LENGTH),
        notch_width_ratio=float(NOTCH_WIDTH_RATIO),
        base_length_x=float(BASE_LENGTH_X),
        base_width_y=float(BASE_WIDTH_Y),
        base_thickness_z=float(BASE_THICKNESS_Z),
        base_overlap_with_neck=float(BASE_OVERLAP_WITH_NECK),
        grasp_cube_length_x=float(GRASP_CUBE_LENGTH_X),
        grasp_cube_width_y=float(GRASP_CUBE_WIDTH_Y),
        grasp_cube_height_z=float(GRASP_CUBE_HEIGHT_Z),
        grasp_cube_center_x_ratio=float(GRASP_CUBE_CENTER_X_RATIO),
        local_base_center=grip_info["base_center"],
        local_cube_center=grip_info["cube_center"],
        local_y_offsets=grip_info["y_offsets"],
        neck_sections_left=grip_info["neck_sections_left"],
        neck_sections_right=grip_info["neck_sections_right"],
        frame_T=T,
        boolean_union_grip_parts=bool(BOOLEAN_UNION_GRIP_PARTS),
        boolean_union_with_model=bool(BOOLEAN_UNION_WITH_MODEL),
    )

    # print("\n========== hole_grip.py done ==========")
    # print("input model STL:", INPUT_STL)
    # print("output STL:", OUTPUT_STL)
    # print("gripper only STL:", GRIPPER_ONLY_STL)
    # print("gripper meta:", GRIPPER_META)
    # print("mark:", mark)
    # print("top_id:", top_id, "side_id:", side_id)
    # print("edge_mid:", edge_mid)
    # print("root_points:\n", root_points)
    # print("h_axis = -top_n:", h_axis)
    # print("edge_axis:", edge_axis)
    # print("z_axis:", z_axis)
    # print("edge extraction info:", edge_info)
    # print("model faces:", len(model_mesh.faces))
    # print("grip faces:", len(grip_world.faces))
    # print("full faces:", len(full_mesh.faces))

    if VISUALIZE:
        full_mesh.show()


if __name__ == "__main__":
    main()
