"""
Depression_gripper_generation_loft.py

Run order:
    Depression_Completion.py
        -> repairModel_mesh.py
        -> Depression_gripper_generation_loft.py
        -> Depression_model_orient_bbox.py

Purpose:
    Add a one-piece PLA gripper onto the depression repair model top plane.

Main change compared with Depression_gripper_generation_v2.py:
    The gripper is no longer generated as three independent meshes
    (base_block + v_neck + grip_body). Instead, it is generated as ONE
    continuous rectangular loft mesh, following the same idea as
    hole_grip_generation.py:

        section 0 -> section 1 -> ... -> section N

    Only the first and last sections have caps. There are no internal caps
    between base / V-neck / grip body, so the gripper itself is one continuous
    shell before it is merged or boolean-unioned with the repair model.

Inputs expected in COMPLETION_DIR:
    model.stl      : generated by repairModel_mesh.py
    meta.npz       : generated by Depression_Completion.py, should contain:
                    - n_axis
                    - repair_point_center and top_plane_center
                    - side_n_mark, or u_axis/v_axis

Outputs:
    model_with_gripper.stl
    gripper_only.stl
    gripper_meta.npz

Geometry definition:
    - attach center   : [repair_point_center.x, repair_point_center.y, top_plane_center.z]
    - height direction: -n_axis, i.e. outward normal of top plane
    - width direction : u_axis
    - length direction: v_axis
    - base, V-neck and grip body are represented by one continuous loft.

Important unit setting:
    If current STL/PCD/meta are in meters, keep MM = 0.001.
    If current STL/PCD/meta are already in millimeters, set MM = 1.0.
"""

import argparse
import os
import numpy as np
import open3d as o3d
import trimesh
from depression_model_postprocess import force_consistent_positive_volume, clean_trimesh

# =========================================================
# User config
# =========================================================
COMPLETION_DIR = r"E:\HKUSTGZ\AAM\construction\data\completion_result\depression"
INPUT_STL = os.path.join(COMPLETION_DIR, "model_processed.stl")
META_PATH = os.path.join(COMPLETION_DIR, "meta.npz")
OUTPUT_STL = os.path.join(COMPLETION_DIR, "model_with_gripper.stl")
GRIPPER_ONLY_STL = os.path.join(COMPLETION_DIR, "gripper_only.stl")
GRIPPER_META = os.path.join(COMPLETION_DIR, "gripper_meta.npz")

# Unit conversion: millimeter -> current model unit.
MM = 0.001

# Small overlap into the model to avoid numerical gap at top surface.
EMBED_DEPTH = 0.3 * MM

BASE_HEIGHT = 1.0 * MM
BASE_WIDTH_U = 8.0 * MM
BASE_LENGTH_V = 8.0 * MM

V_NECK_HEIGHT = 2.0 * MM
V_NECK_MIN_WIDTH_U = 1.0 * MM
V_NECK_MIN_LENGTH_V = 1.0 * MM
V_NECK_SECTION_NUM = 15

GRIP_BODY_HEIGHT = 15.0 * MM
GRIP_BODY_WIDTH_U = 3.0 * MM
GRIP_BODY_LENGTH_V = 3.0 * MM

VISUALIZE = False
BOOLEAN = True  # TRUE: boolean union model and gripper; FALSE: concatenate two meshes.

# =========================================================
# Basic utils
# =========================================================
def normalize(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=float).reshape(3)
    n = np.linalg.norm(v)
    if n < 1e-12:
        raise ValueError(f"zero-length vector: {v}")
    return v / n


def unwrap_np_value(x):
    if isinstance(x, np.ndarray):
        if x.shape == ():
            return x.item()
        return x
    return x


def load_meta(meta_path: str):
    if not os.path.exists(meta_path):
        raise FileNotFoundError(f"Cannot find meta.npz: {meta_path}")

    data = np.load(meta_path, allow_pickle=True)

    if "n_axis" not in data.files:
        raise KeyError("meta.npz must contain n_axis")

    meta = {k: unwrap_np_value(data[k]) for k in data.files}
    meta["n_axis"] = normalize(np.asarray(meta["n_axis"], dtype=float))

    if "top_plane_center" not in meta:
        raise KeyError("meta.npz must contain top_plane_center")
    if "repair_point_center" not in meta:
        raise KeyError("meta.npz must contain repair_point_center")

    top_plane_center = np.asarray(meta["top_plane_center"], dtype=float).reshape(3)
    repair_point_center = np.asarray(meta["repair_point_center"], dtype=float).reshape(3)

    # 保持原代码逻辑：xy 来自 repair_point_center，z 来自 top_plane_center。
    # 注意：如果 repair_point_center 在极端缺陷中落在无实体区域，attach_center 仍可能悬空。
    attach_center = np.asarray([
        repair_point_center[0],
        repair_point_center[1],
        top_plane_center[2],
    ], dtype=float)

    meta["attach_center"] = attach_center
    return meta


def recover_uv_axes(meta: dict):
    """
    Recover u_axis and v_axis.

    Best case:
        meta.npz already contains u_axis and v_axis.

    Current completion scripts save outward normals directly:
        max_u_outward = +u_axis
        max_v_outward = +v_axis
        min_v_outward = -v_axis
    """
    n_axis = normalize(meta["n_axis"])

    if "u_axis" in meta and "v_axis" in meta:
        u_axis = normalize(np.asarray(meta["u_axis"], dtype=float))
        v_axis = normalize(np.asarray(meta["v_axis"], dtype=float))
        return u_axis, v_axis

    if "side_n_mark" not in meta:
        raise KeyError("meta.npz must contain either u_axis/v_axis or side_n_mark")

    side_n_mark = meta["side_n_mark"]
    if not isinstance(side_n_mark, dict):
        raise TypeError(f"side_n_mark should be dict, got {type(side_n_mark)}")

    if "max_u_outward" in side_n_mark:
        u_axis = normalize(np.asarray(side_n_mark["max_u_outward"], dtype=float))
    else:
        raise KeyError("Cannot recover u_axis from side_n_mark. Need max_u_outward.")

    if "max_v_outward" in side_n_mark:
        v_axis = normalize(np.asarray(side_n_mark["max_v_outward"], dtype=float))
    elif "min_v_outward" in side_n_mark:
        v_axis = -normalize(np.asarray(side_n_mark["min_v_outward"], dtype=float))
    else:
        v_axis = normalize(np.cross(n_axis, u_axis))

    # Re-orthogonalize.
    u_axis = normalize(u_axis - np.dot(u_axis, n_axis) * n_axis)
    v_axis = normalize(v_axis - np.dot(v_axis, n_axis) * n_axis - np.dot(v_axis, u_axis) * u_axis)

    if np.dot(np.cross(u_axis, v_axis), n_axis) < 0:
        v_axis = -v_axis

    return u_axis, v_axis


# =========================================================
# Continuous loft gripper construction
# =========================================================
def build_v_neck_sections(s0, s1):
    """
    Build V-neck sections.

    The size profile is:
        bottom: same as base block
        middle: narrow waist
        top   : same as grip body

    This produces V-shaped / dog-bone shrink-expand transition.
    """
    if V_NECK_SECTION_NUM < 3:
        n_sec = 3
    else:
        n_sec = int(V_NECK_SECTION_NUM)
    if n_sec % 2 == 0:
        n_sec += 1

    sections = []
    for i in range(n_sec):
        t = i / (n_sec - 1)
        s = s0 + t * (s1 - s0)

        if t <= 0.5:
            # base -> waist
            a = t / 0.5
            size_u = (1.0 - a) * BASE_WIDTH_U + a * V_NECK_MIN_WIDTH_U
            size_v = (1.0 - a) * BASE_LENGTH_V + a * V_NECK_MIN_LENGTH_V
        else:
            # waist -> grip body
            a = (t - 0.5) / 0.5
            size_u = (1.0 - a) * V_NECK_MIN_WIDTH_U + a * GRIP_BODY_WIDTH_U
            size_v = (1.0 - a) * V_NECK_MIN_LENGTH_V + a * GRIP_BODY_LENGTH_V

        sections.append((float(s), float(size_u), float(size_v)))

    return sections


def remove_duplicate_s_sections(sections, eps=1e-12):
    """
    Remove repeated sections with the same s value to avoid zero-length faces.
    If two sections have the same s, keep the latter one.
    """
    sections = sorted(sections, key=lambda x: x[0])
    cleaned = []
    for sec in sections:
        if cleaned and abs(sec[0] - cleaned[-1][0]) < eps:
            cleaned[-1] = sec
        else:
            cleaned.append(sec)
    return cleaned


def build_gripper_loft_sections():
    """
    Build one continuous section list for the whole gripper.

    s = 0 is the model top surface.
    s < 0 means the gripper is embedded into the repair model.
    s > 0 means the gripper grows outward along h_axis = -n_axis.

    This is the depression version of hole_grip's create_grip_local():
    one section list, one side wall connection, only two end caps.
    """
    vneck_s0 = BASE_HEIGHT
    vneck_s1 = BASE_HEIGHT + V_NECK_HEIGHT
    grip_s1 = vneck_s1 + GRIP_BODY_HEIGHT

    sections = []

    # Embedded base and lower base block. Keeping s=0 makes the contact plane explicit,
    # similar to hole_grip's x0=-embed_depth and x1=0.
    sections.append((-EMBED_DEPTH, BASE_WIDTH_U, BASE_LENGTH_V))
    sections.append((0.0, BASE_WIDTH_U, BASE_LENGTH_V))
    sections.append((BASE_HEIGHT, BASE_WIDTH_U, BASE_LENGTH_V))

    # V-neck transition. Exclude the first section because BASE_HEIGHT already exists.
    vneck_sections = build_v_neck_sections(vneck_s0, vneck_s1)
    sections.extend(vneck_sections[1:])

    # Grip body constant section. vneck_sections already ends at vneck_s1 with grip-body size.
    sections.append((grip_s1, GRIP_BODY_WIDTH_U, GRIP_BODY_LENGTH_V))

    return remove_duplicate_s_sections(sections), vneck_s0, vneck_s1, grip_s1


def create_rectangular_loft_trimesh(
    surface_center: np.ndarray,
    u_axis: np.ndarray,
    v_axis: np.ndarray,
    h_axis: np.ndarray,
    sections: list,
):
    """
    Create a continuous rectangular loft mesh from sections.

    sections:
        list of (s, size_u, size_v), sorted along h_axis.

    Local frame:
        local x equivalent = s along h_axis
        local y equivalent = u_axis, section width
        local z equivalent = v_axis, section length

    This follows the same topology as hole_grip_generation.py's
    create_rectangular_loft(): adjacent rectangles are connected directly;
    only start and end caps are added.
    """
    surface_center = np.asarray(surface_center, dtype=float).reshape(3)
    u_axis = normalize(u_axis)
    v_axis = normalize(v_axis)
    h_axis = normalize(h_axis)

    if len(sections) < 2:
        raise ValueError("Need at least two loft sections")

    sections = remove_duplicate_s_sections(sections)
    vertices = []
    faces = []

    for s, size_u, size_v in sections:
        center = surface_center + float(s) * h_axis
        hu = 0.5 * float(size_u)
        hv = 0.5 * float(size_v)

        # Same vertex order for every section.
        vertices.extend([
            center - hu * u_axis - hv * v_axis,
            center + hu * u_axis - hv * v_axis,
            center + hu * u_axis + hv * v_axis,
            center - hu * u_axis + hv * v_axis,
        ])

    # Side faces between adjacent sections.
    for i in range(len(sections) - 1):
        a = 4 * i
        b = 4 * (i + 1)
        quads = [
            [a + 0, a + 1, b + 1, b + 0],
            [a + 1, a + 2, b + 2, b + 1],
            [a + 2, a + 3, b + 3, b + 2],
            [a + 3, a + 0, b + 0, b + 3],
        ]
        for q in quads:
            faces.append([q[0], q[1], q[2]])
            faces.append([q[0], q[2], q[3]])

    # Start cap only.
    faces.append([0, 2, 1])
    faces.append([0, 3, 2])

    # End cap only.
    last = 4 * (len(sections) - 1)
    faces.append([last + 0, last + 1, last + 2])
    faces.append([last + 0, last + 2, last + 3])

    mesh = trimesh.Trimesh(
        vertices=np.asarray(vertices, dtype=float),
        faces=np.asarray(faces, dtype=np.int64),
        process=True,
    )
    mesh.remove_unreferenced_vertices()
    mesh.fix_normals()
    return mesh


def create_gripper_loft_mesh(
    surface_center: np.ndarray,
    u_axis: np.ndarray,
    v_axis: np.ndarray,
    h_axis: np.ndarray,
):
    """
    Create the whole gripper as a single continuous loft mesh.
    """
    sections, vneck_s0, vneck_s1, grip_s1 = build_gripper_loft_sections()
    gripper_tri = create_rectangular_loft_trimesh(
        surface_center=surface_center,
        u_axis=u_axis,
        v_axis=v_axis,
        h_axis=h_axis,
        sections=sections,
    )
    #gripper_o3d = trimesh_to_o3d(gripper_tri)
    return gripper_tri, sections, vneck_s0, vneck_s1, grip_s1


# =========================================================
# Mesh conversion / merge / boolean
# =========================================================
def merge_meshes(meshes):
    if all(isinstance(m, trimesh.Trimesh) for m in meshes):
        merged = trimesh.util.concatenate(meshes)
        merged = clean_trimesh(merged)
        return merged

    merged = o3d.geometry.TriangleMesh()
    for m in meshes:
        merged += m
    merged.remove_duplicated_vertices()
    merged.remove_duplicated_triangles()
    merged.remove_degenerate_triangles()
    merged.remove_unreferenced_vertices()
    merged.compute_vertex_normals()
    return merged


def o3d_to_trimesh(mesh_o3d):
    v = np.asarray(mesh_o3d.vertices)
    f = np.asarray(mesh_o3d.triangles)
    return trimesh.Trimesh(vertices=v, faces=f, process=True)


def trimesh_to_o3d(mesh_tri):
    mesh_o3d = o3d.geometry.TriangleMesh()
    mesh_o3d.vertices = o3d.utility.Vector3dVector(np.asarray(mesh_tri.vertices))
    mesh_o3d.triangles = o3d.utility.Vector3iVector(np.asarray(mesh_tri.faces, dtype=np.int32))
    mesh_o3d.remove_duplicated_vertices()
    mesh_o3d.remove_duplicated_triangles()
    mesh_o3d.remove_degenerate_triangles()
    mesh_o3d.remove_unreferenced_vertices()
    mesh_o3d.compute_vertex_normals()
    return mesh_o3d


def boolean_union(mesh_a, mesh_b):
    try:
        union = trimesh.boolean.union(
            [mesh_a, mesh_b],
            engine="manifold",
        )
    except ModuleNotFoundError as exc:
        print(f"Boolean union skipped: {exc}. Falling back to mesh concatenate.")
        return merge_meshes([mesh_a, mesh_b])
    except BaseException as exc:
        print(f"Boolean union failed: {exc}. Falling back to mesh concatenate.")
        return merge_meshes([mesh_a, mesh_b])

    if union is None:
        print("Boolean union returned None. Falling back to mesh concatenate.")
        return merge_meshes([mesh_a, mesh_b])

    return union

    union = trimesh.boolean.union(
        [mesh_a, mesh_b],
        engine="manifold" ) # 如果不可用，改成 "blender"

    if union is None:
        raise RuntimeError("Boolean union failed")

    return union

# =========================================================
# Main
# =========================================================
def main():
    meta = load_meta(META_PATH)

    n_axis = normalize(meta["n_axis"])
    h_axis = -n_axis
    attach_center = meta["attach_center"]
    u_axis, v_axis = recover_uv_axes(meta)

    if not os.path.exists(INPUT_STL):
        raise FileNotFoundError(f"Cannot find input STL from repairModel_mesh.py: {INPUT_STL}")

    model_mesh = trimesh.load(INPUT_STL, force="mesh", process=True)
    model_mesh = force_consistent_positive_volume(clean_trimesh(model_mesh))
    if len(model_mesh.vertices) == 0:
        raise RuntimeError(f"Empty mesh: {INPUT_STL}")
    model_mesh.vertex_normals

    gripper_mesh, loft_sections, vneck_s0, vneck_s1, grip_s1 = create_gripper_loft_mesh(
        surface_center=attach_center,
        u_axis=u_axis,
        v_axis=v_axis,
        h_axis=h_axis,
    )

    print("model watertight:", model_mesh.is_watertight)
    print("model volume:", model_mesh.is_volume)
    print("model winding consistent:", model_mesh.is_winding_consistent)

    print("gripper watertight:", gripper_mesh.is_watertight)
    print("gripper volume:", gripper_mesh.is_volume)
    print("gripper winding consistent:", gripper_mesh.is_winding_consistent)
    print("gripper loft section count:", len(loft_sections))

    if BOOLEAN is True:
        # 这个函数让 GRIP 与 repair model 不再是两个分割的实体，拼成一个整体。
        full_mesh = boolean_union(model_mesh, gripper_mesh)
    elif BOOLEAN is False:
        # 保持原逻辑：不做 boolean，只把两个 mesh 写在同一个 STL 中。
        full_mesh = merge_meshes([model_mesh, gripper_mesh])
    else:
        raise ValueError("BOOLEAN must be True or False")

    os.makedirs(COMPLETION_DIR, exist_ok=True)
    #ok1 = o3d.io.write_triangle_mesh(GRIPPER_ONLY_STL, gripper_mesh)
    #ok2 = o3d.io.write_triangle_mesh(OUTPUT_STL, full_mesh)
    gripper_mesh.export(GRIPPER_ONLY_STL)
    full_mesh.export(OUTPUT_STL)

    np.savez(
        GRIPPER_META,
        attach_center=attach_center,
        n_axis=n_axis,
        h_axis=h_axis,
        u_axis=u_axis,
        v_axis=v_axis,
        mm=float(MM),
        embed_depth=float(EMBED_DEPTH),
        base_height=float(BASE_HEIGHT),
        base_width_u=float(BASE_WIDTH_U),
        base_length_v=float(BASE_LENGTH_V),
        v_neck_start_height=float(vneck_s0),
        v_neck_height=float(V_NECK_HEIGHT),
        v_neck_end_height=float(vneck_s1),
        v_neck_min_width_u=float(V_NECK_MIN_WIDTH_U),
        v_neck_min_length_v=float(V_NECK_MIN_LENGTH_V),
        v_neck_section_num=int(V_NECK_SECTION_NUM),
        grip_body_height=float(GRIP_BODY_HEIGHT),
        grip_body_width_u=float(GRIP_BODY_WIDTH_U),
        grip_body_length_v=float(GRIP_BODY_LENGTH_V),
        grip_top_height=float(grip_s1),
        loft_sections=np.asarray(loft_sections, dtype=float),
        output_stl=OUTPUT_STL,
        gripper_only_stl=GRIPPER_ONLY_STL,
        boolean=bool(BOOLEAN),
    )

    print("\n========== Depression gripper generation loft done ==========")
    print("input model STL:", INPUT_STL)
    print("output STL:", OUTPUT_STL)
    print("gripper only STL:", GRIPPER_ONLY_STL)
    print("gripper meta:", GRIPPER_META)
    print("attach center:", attach_center)
    print("height direction h_axis = -n_axis:", h_axis)
    print("width direction u_axis:", u_axis)
    print("length direction v_axis:", v_axis)
    print("V-neck starts at:", vneck_s0, "model unit")
    print("V-neck ends at:", vneck_s1, "model unit")
    print("V-neck waist size [u, v]:", V_NECK_MIN_WIDTH_U, V_NECK_MIN_LENGTH_V)
    print("Grip top height:", grip_s1, "model unit")

    if VISUALIZE:
        model_show = o3d.geometry.TriangleMesh(model_mesh)
        gripper_show = o3d.geometry.TriangleMesh(gripper_mesh)

        model_show.paint_uniform_color([0.65, 0.65, 0.65])
        gripper_show.paint_uniform_color([0.65, 0.65, 0.65])

        frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.06)
        o3d.visualization.draw_geometries(
            [model_show, gripper_show, frame]
        )


def parse_args():
    parser = argparse.ArgumentParser(description="Generate depression gripper mesh.")
    parser.add_argument("--completion-dir", type=str, default=None, help="Completion output directory.")
    parser.add_argument("--input-stl", type=str, default=None, help="Input repair model STL.")
    parser.add_argument("--meta", type=str, default=None, help="Input completion meta.npz.")
    parser.add_argument("--output-stl", type=str, default=None, help="Output model_with_gripper STL.")
    parser.add_argument("--gripper-only-stl", type=str, default=None, help="Output gripper-only STL.")
    parser.add_argument("--gripper-meta", type=str, default=None, help="Output gripper_meta.npz.")
    parser.add_argument("--visualize", action="store_true", help="Show Open3D visualization.")
    parser.add_argument("--no-boolean", action="store_true", help="Concatenate model and gripper instead of boolean union.")
    return parser.parse_args()


def configure_from_args(args):
    global COMPLETION_DIR, INPUT_STL, META_PATH, OUTPUT_STL
    global GRIPPER_ONLY_STL, GRIPPER_META, VISUALIZE, BOOLEAN

    if args.completion_dir is not None:
        COMPLETION_DIR = args.completion_dir
        INPUT_STL = os.path.join(COMPLETION_DIR, "model_processed.stl")
        META_PATH = os.path.join(COMPLETION_DIR, "meta.npz")
        OUTPUT_STL = os.path.join(COMPLETION_DIR, "model_with_gripper.stl")
        GRIPPER_ONLY_STL = os.path.join(COMPLETION_DIR, "gripper_only.stl")
        GRIPPER_META = os.path.join(COMPLETION_DIR, "gripper_meta.npz")
    if args.input_stl is not None:
        INPUT_STL = args.input_stl
    if args.meta is not None:
        META_PATH = args.meta
    if args.output_stl is not None:
        OUTPUT_STL = args.output_stl
    if args.gripper_only_stl is not None:
        GRIPPER_ONLY_STL = args.gripper_only_stl
    if args.gripper_meta is not None:
        GRIPPER_META = args.gripper_meta
    if args.visualize:
        VISUALIZE = True
    if args.no_boolean:
        BOOLEAN = False


if __name__ == "__main__":
    configure_from_args(parse_args())
    main()
