"""
hole_model_orient.py

Purpose
-------
Orient the full hole repair model with gripper into a standardized STL frame.

Input files are generated by previous steps:
    Hole_Completion.py      -> meta.npz, mark.json, model.pcd, defect/plane pcds
    repairModel_mesh.py     -> model.stl
    hole_grip.py            -> model_with_gripper.stl, gripper_only.stl, gripper_meta.npz

New coordinate definition
-------------------------
    +Z axis <- top_n_inward
    +Y axis <- side_n_inward
    +X axis <- right-hand rule, computed from +Y and +Z
    origin  <- bounding-box center of the whole model_with_gripper after rotation

Unit
----
Input STL is already in meters. No unit scaling is applied.

Main saved outputs
------------------
    model_with_gripper_oriented.stl
    model_oriented.stl                    # same full model, convenient alias
    model_repair_oriented.stl             # repair-only model if model.stl exists
    gripper_only_oriented.stl             # gripper-only model if gripper_only.stl exists
    orientation_meta.npz                  # contains T, R, t and transformed metadata
    orientation_meta.json                 # readable summary
"""

from __future__ import annotations
import json
from pathlib import Path
from typing import Dict, Any
import numpy as np
import open3d as o3d


# =========================================================
# User config
# =========================================================
COMPLETION_DIR = Path(r"E:\HKUSTGZ\AAM\construction\data\completion_result\hole")

INPUT_FULL_STL = COMPLETION_DIR / "model_with_gripper.stl"
INPUT_REPAIR_STL = COMPLETION_DIR / "model.stl"
INPUT_GRIPPER_STL = COMPLETION_DIR / "gripper_only.stl"

META_PATH = COMPLETION_DIR / "meta.npz"
GRIPPER_META_PATH = COMPLETION_DIR / "gripper_meta.npz"

OUTPUT_FULL_STL = COMPLETION_DIR / "model_with_gripper_oriented.stl"
OUTPUT_FULL_STL_ALIAS = COMPLETION_DIR / "model_oriented.stl"
OUTPUT_REPAIR_STL = COMPLETION_DIR / "model_repair_oriented.stl"
OUTPUT_GRIPPER_STL = COMPLETION_DIR / "gripper_only_oriented.stl"

ORIENTATION_META_PATH = COMPLETION_DIR / "orientation_meta.npz"
ORIENTATION_JSON_PATH = COMPLETION_DIR / "orientation_meta.json"

VISUALIZE = False


# =========================================================
# Basic utils
# =========================================================
def normalize(v: np.ndarray) -> np.ndarray:
    v = np.asarray(v, dtype=float).reshape(3)
    n = np.linalg.norm(v)
    if n < 1e-12:
        raise ValueError(f"zero-length vector: {v}")
    return v / n


def make_T(R: np.ndarray, t: np.ndarray) -> np.ndarray:
    T = np.eye(4, dtype=float)
    T[:3, :3] = np.asarray(R, dtype=float).reshape(3, 3)
    T[:3, 3] = np.asarray(t, dtype=float).reshape(3)
    return T


def transform_points(points: np.ndarray, R: np.ndarray, t: np.ndarray) -> np.ndarray:
    pts = np.asarray(points, dtype=float)
    return (R @ pts.T).T + t.reshape(1, 3)


def transform_dirs(dirs: np.ndarray, R: np.ndarray) -> np.ndarray:
    arr = np.asarray(dirs, dtype=float)
    if arr.ndim == 1:
        return R @ arr
    return (R @ arr.T).T


def bbox_from_points(points: np.ndarray):
    pts = np.asarray(points, dtype=float)
    bmin = pts.min(axis=0)
    bmax = pts.max(axis=0)
    center = 0.5 * (bmin + bmax)
    size = bmax - bmin
    return bmin, bmax, center, size


def read_mesh(path: Path) -> o3d.geometry.TriangleMesh:
    mesh = o3d.io.read_triangle_mesh(str(path))
    if len(mesh.vertices) == 0 or len(mesh.triangles) == 0:
        raise RuntimeError(f"Empty mesh: {path}")
    return mesh


def write_mesh_with_transform(input_path: Path, output_path: Path, R: np.ndarray, t: np.ndarray):
    mesh = read_mesh(input_path)
    v = np.asarray(mesh.vertices, dtype=float)
    mesh.vertices = o3d.utility.Vector3dVector(transform_points(v, R, t))
    mesh.compute_vertex_normals()
    ok = o3d.io.write_triangle_mesh(str(output_path), mesh)
    if not ok:
        raise RuntimeError(f"Failed to write mesh: {output_path}")
    return mesh


def write_pcd_with_transform(input_path: Path, output_path: Path, R: np.ndarray, t: np.ndarray):
    if not input_path.exists():
        return ""
    pcd = o3d.io.read_point_cloud(str(input_path))
    pts = np.asarray(pcd.points, dtype=float)
    if len(pts) == 0:
        return ""
    pcd.points = o3d.utility.Vector3dVector(transform_points(pts, R, t))
    o3d.io.write_point_cloud(str(output_path), pcd)
    return str(output_path)


def transform_plane(plane_model: np.ndarray, R: np.ndarray, t: np.ndarray) -> np.ndarray:
    """
    Original plane: n^T p + d = 0.
    New point: q = R p + t.
    New plane: (R n)^T q + (d - (R n)^T t) = 0.
    """
    p = np.asarray(plane_model, dtype=float).reshape(4)
    n = p[:3]
    d = float(p[3])
    s = np.linalg.norm(n)
    if s < 1e-12:
        raise ValueError(f"Invalid plane model: {plane_model}")
    n = n / s
    d = d / s
    n_new = R @ n
    d_new = d - float(n_new @ t)
    return np.r_[n_new, d_new]


def orient_plane_to_normal(plane_model: np.ndarray, target_normal: np.ndarray) -> np.ndarray:
    p = np.asarray(plane_model, dtype=float).reshape(4)
    n = normalize(p[:3])
    d = float(p[3]) / np.linalg.norm(p[:3])
    p = np.r_[n, d]
    if float(p[:3] @ normalize(target_normal)) < 0:
        p = -p
    return p


def to_jsonable(x: Any):
    if isinstance(x, np.ndarray):
        return x.tolist()
    if isinstance(x, (np.float32, np.float64)):
        return float(x)
    if isinstance(x, (np.int32, np.int64)):
        return int(x)
    if isinstance(x, Path):
        return str(x)
    return x


# =========================================================
# Rotation construction
# =========================================================
def make_rotation_from_top_side(top_n_inward: np.ndarray, side_n_inward: np.ndarray):
    """
    Construct R for column-vector transform p_new = R @ p_old + t.

    Enforced:
        R @ top_n_inward = [0, 0, 1]
        R @ side_n_inward ~= [0, 1, 0]

    If top_n and side_n are not exactly perpendicular, side_n is projected to
    the plane perpendicular to top_n. This keeps top plane exactly parallel to XOY.
    """
    z_src = normalize(top_n_inward)

    y_src_raw = normalize(side_n_inward)
    y_src = y_src_raw - float(y_src_raw @ z_src) * z_src
    y_src = normalize(y_src)
    if float(y_src @ y_src_raw) < 0:
        y_src = -y_src

    x_src = normalize(np.cross(y_src, z_src))

    # Source basis columns are old-frame directions that should become +X,+Y,+Z.
    S = np.column_stack([x_src, y_src, z_src])
    R = S.T

    # Numerical cleanup: nearest proper rotation.
    U, _, Vt = np.linalg.svd(R)
    R = U @ Vt
    if np.linalg.det(R) < 0:
        U[:, -1] *= -1
        R = U @ Vt

    source_basis = np.column_stack([x_src, y_src, z_src])
    return R, source_basis


# =========================================================
# Main
# =========================================================
def main():
    COMPLETION_DIR.mkdir(parents=True, exist_ok=True)

    gripper_meta = np.load(str(GRIPPER_META_PATH), allow_pickle=True)
    meta = np.load(str(META_PATH), allow_pickle=True)

    top_id = int(gripper_meta["top_id"])
    side_id = int(gripper_meta["side_id"])
    top_n = normalize(gripper_meta["top_n_inward"])
    side_n = normalize(gripper_meta["side_n_inward"])

    R, source_basis = make_rotation_from_top_side(top_n, side_n)

    # Read and rotate the full model with gripper. No unit scale is used.
    full_mesh = read_mesh(INPUT_FULL_STL)
    vertices = np.asarray(full_mesh.vertices, dtype=float)
    vertices_rot = (R @ vertices.T).T

    bbox_min_rot, bbox_max_rot, bbox_center_rot, bbox_size_rot = bbox_from_points(vertices_rot)
    t = -bbox_center_rot
    vertices_out = vertices_rot + t.reshape(1, 3)

    T = make_T(R, t)
    T_inv = np.linalg.inv(T)

    full_mesh.vertices = o3d.utility.Vector3dVector(vertices_out)
    full_mesh.compute_vertex_normals()
    o3d.io.write_triangle_mesh(str(OUTPUT_FULL_STL), full_mesh)
    #o3d.io.write_triangle_mesh(str(OUTPUT_FULL_STL_ALIAS), full_mesh)

    bbox_min_after, bbox_max_after, bbox_center_after, bbox_size_after = bbox_from_points(vertices_out)

    # Transform repair-only and gripper-only STL for debugging / downstream use.
    repair_bbox_center_after = np.full(3, np.nan)
    repair_bbox_min_after = np.full(3, np.nan)
    repair_bbox_max_after = np.full(3, np.nan)
    full_T_repair = np.eye(4)

    if INPUT_REPAIR_STL.exists():
        repair_mesh = write_mesh_with_transform(INPUT_REPAIR_STL, OUTPUT_REPAIR_STL, R, t)
        repair_vertices_out = np.asarray(repair_mesh.vertices, dtype=float)
        repair_bbox_min_after, repair_bbox_max_after, repair_bbox_center_after, _ = bbox_from_points(repair_vertices_out)
        full_T_repair[:3, 3] = repair_bbox_center_after

    if INPUT_GRIPPER_STL.exists():
        write_mesh_with_transform(INPUT_GRIPPER_STL, OUTPUT_GRIPPER_STL, R, t)

    # Transform common point clouds saved by previous steps.
    oriented_pcd_paths: Dict[str, str] = {}
    for name in ["model", "defect_pcd1", "defect_pcd2", "plane1_pcd", "plane2_pcd"]:
        in_p = COMPLETION_DIR / f"{name}.pcd"
        out_p = COMPLETION_DIR / f"{name}_oriented.pcd"
        out = write_pcd_with_transform(in_p, out_p, R, t)
        if out:
            oriented_pcd_paths[name] = out

    # Transform key points from gripper_meta.
    edge_mid = np.asarray(gripper_meta["edge_mid"], dtype=float).reshape(3)
    root_points = np.asarray(gripper_meta["root_points"], dtype=float).reshape(-1, 3)
    edge_mid_oriented = R @ edge_mid + t
    root_points_oriented = transform_points(root_points, R, t)

    frame_T = np.asarray(gripper_meta["frame_T"], dtype=float).reshape(4, 4)
    frame_T_oriented = T @ frame_T

    # Transform key points and planes from Hole_Completion meta.
    plane1_model_oriented = transform_plane(meta["plane1_model"], R, t)
    plane2_model_oriented = transform_plane(meta["plane2_model"], R, t)
    top_plane_oriented = transform_plane(meta[f"plane{top_id}_model"], R, t)
    side_plane_oriented = transform_plane(meta[f"plane{side_id}_model"], R, t)

    plane1_center_oriented = R @ np.asarray(meta["plane1_center"], dtype=float).reshape(3) + t
    plane2_center_oriented = R @ np.asarray(meta["plane2_center"], dtype=float).reshape(3) + t
    object_center_oriented = R @ np.asarray(meta["object_center"], dtype=float).reshape(3) + t
    defect1_center_oriented = R @ np.asarray(meta["defect1_center"], dtype=float).reshape(3) + t
    defect2_center_oriented = R @ np.asarray(meta["defect2_center"], dtype=float).reshape(3) + t

    # Save everything needed for downstream transform tracking.
    np.savez(
        str(ORIENTATION_META_PATH),
        T=T,
        T_inv=T_inv,
        R=R,
        t=t,
        input_full_stl=str(INPUT_FULL_STL),
        output_full_stl=str(OUTPUT_FULL_STL),
        output_full_stl_alias=str(OUTPUT_FULL_STL_ALIAS),
        input_repair_stl=str(INPUT_REPAIR_STL),
        output_repair_stl=str(OUTPUT_REPAIR_STL),
        input_gripper_stl=str(INPUT_GRIPPER_STL),
        output_gripper_stl=str(OUTPUT_GRIPPER_STL),
        meta_path=str(META_PATH),
        gripper_meta_path=str(GRIPPER_META_PATH),
        unit_scale=1.0,
        top_id=top_id,
        side_id=side_id,
        top_n_inward=top_n,
        side_n_inward=side_n,
        x_axis_src=source_basis[:, 0],
        y_axis_src=source_basis[:, 1],
        z_axis_src=source_basis[:, 2],
        top_n_after=R @ top_n,
        side_n_after=R @ side_n,
        bbox_min_rot=bbox_min_rot,
        bbox_max_rot=bbox_max_rot,
        bbox_center_rot=bbox_center_rot,
        bbox_size_rot=bbox_size_rot,
        bbox_min_after=bbox_min_after,
        bbox_max_after=bbox_max_after,
        bbox_center_after=bbox_center_after,
        bbox_size_after=bbox_size_after,
        full_box_x=float(bbox_size_after[0]),
        full_box_y=float(bbox_size_after[1]),
        full_box_z=float(bbox_size_after[2]),
        repair_bbox_min_after=repair_bbox_min_after,
        repair_bbox_max_after=repair_bbox_max_after,
        repair_bbox_center_after=repair_bbox_center_after,
        full_T_repair=full_T_repair,
        repair_T_full=np.linalg.inv(full_T_repair),
        edge_mid=edge_mid,
        edge_mid_oriented=edge_mid_oriented,
        root_points=root_points,
        root_points_oriented=root_points_oriented,
        frame_T=frame_T,
        frame_T_oriented=frame_T_oriented,
        plane1_model=meta["plane1_model"],
        plane2_model=meta["plane2_model"],
        plane1_model_oriented=plane1_model_oriented,
        plane2_model_oriented=plane2_model_oriented,
        top_plane_oriented=top_plane_oriented,
        side_plane_oriented=side_plane_oriented,
        plane1_center_oriented=plane1_center_oriented,
        plane2_center_oriented=plane2_center_oriented,
        object_center_oriented=object_center_oriented,
        defect1_center_oriented=defect1_center_oriented,
        defect2_center_oriented=defect2_center_oriented,
        oriented_model_pcd_path=oriented_pcd_paths.get("model", ""),
        oriented_defect_pcd1_path=oriented_pcd_paths.get("defect_pcd1", ""),
        oriented_defect_pcd2_path=oriented_pcd_paths.get("defect_pcd2", ""),
        oriented_plane1_pcd_path=oriented_pcd_paths.get("plane1_pcd", ""),
        oriented_plane2_pcd_path=oriented_pcd_paths.get("plane2_pcd", ""),
    )

    summary = {
        "input_full_stl": str(INPUT_FULL_STL),
        "output_full_stl": str(OUTPUT_FULL_STL),
        "output_full_stl_alias": str(OUTPUT_FULL_STL_ALIAS),
        "orientation_meta": str(ORIENTATION_META_PATH),
        "unit_scale": 1.0,
        "top_id": top_id,
        "side_id": side_id,
        "top_n_after": R @ top_n,
        "side_n_after": R @ side_n,
        "bbox_min_after": bbox_min_after,
        "bbox_max_after": bbox_max_after,
        "bbox_center_after": bbox_center_after,
        "bbox_size_after": bbox_size_after,
        "T": T,
        "full_T_repair": full_T_repair,
        "edge_mid_oriented": edge_mid_oriented,
        "root_points_oriented": root_points_oriented,
    }
    with open(ORIENTATION_JSON_PATH, "w", encoding="utf-8") as f:
        json.dump({k: to_jsonable(v) for k, v in summary.items()}, f, indent=2, ensure_ascii=False)

    print("\n========== hole model orientation done ==========")
    print("input full STL:", INPUT_FULL_STL)
    print("output full STL:", OUTPUT_FULL_STL)
    print("output alias:", OUTPUT_FULL_STL_ALIAS)
    print("orientation meta:", ORIENTATION_META_PATH)
    print("unit_scale: 1.0, no unit conversion")
    print("top_n_after:", R @ top_n)
    print("side_n_after:", R @ side_n)
    print("bbox_center_after:", bbox_center_after)
    print("bbox_size_after:", bbox_size_after)
    print("T:\n", T)

    if VISUALIZE:
        mesh_show = o3d.geometry.TriangleMesh(full_mesh)
        mesh_show.paint_uniform_color([0.7, 0.7, 0.7])
        frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=max(0.02, float(np.linalg.norm(bbox_size_after)) * 0.25))
        o3d.visualization.draw_geometries([mesh_show, frame])


if __name__ == "__main__":
    main()
