from io import BytesIO
import time
import zipfile
import bambulabs_api as bl
import os

IP = '10.41.3.35'
SERIAL = '0309AA441000235'
ACCESS_CODE = '11215887'

# ============================================================
# This example is designed to work with 3mf files generated by
# OrcaSlicer
# ============================================================
INPUT_FILE_PATH = '/home/smmg/AAM/model2print/data/whole_model_sliced.3mf'
# ============================================================

env = os.getenv("env", "debug")


def gcode_files_in_3mf(
        zipfile_path: str) -> list[str]:
    """
    Get the gcodefiles in the 3mf.

    Args:
        zipfile_path (str): location of the text file.

    Returns:
        list[str]: first gcode file, or None if not found
    """
    zf = zipfile.ZipFile(zipfile_path)

    nl = zf.namelist()
    print(nl)
    return [n for n in nl if n.endswith(".gcode") and n.startswith("Metadata/plate_")]  # noqa: E501


if __name__ == '__main__':
    print('Starting bambulabs_api example')
    print('Connecting to Bambulabs 3D printer')
    print(f'IP: {IP}')
    print(f'Serial: {SERIAL}')
    print(f'Access Code: {ACCESS_CODE}')

    printer = bl.Printer(IP, ACCESS_CODE, SERIAL)
    printer.connect()

    time.sleep(5)

    # 检查 3MF 内部是否真的有已切片 gcode
    gcode_location = next(
        (i for i in gcode_files_in_3mf(INPUT_FILE_PATH)), None
    )

    if not gcode_location:
        print("No gcode file found in 3mf")
        exit(1)

    print(f"Found gcode in 3mf: {gcode_location}")

    # 关键：打印机端文件名，不要用 /home/... 这种本地绝对路径
    remote_filename = os.path.basename(INPUT_FILE_PATH)

    with open(INPUT_FILE_PATH, "rb") as file:
        io_file = BytesIO(file.read())

    result = printer.upload_file(io_file, remote_filename)
    print(f"Upload result: {result}")

    if result is None or "226" not in str(result):
        print("Error Uploading File to Printer")
        exit(1)

    print("Done Uploading File")

    # 关键：start_print 也用 remote_filename，不用本地路径
    printer.start_print(remote_filename,1,use_ams=False,flow_calibration=False)

    print("Start Print Command Sent")