# -*- coding: utf-8 -*-
"""
hole_orientation.py

Purpose
-------
Standardize the pose of the hole repair model after the grip has been joined.

Input
-----
1) model_with_gripper.stl generated by hole_grip.py
2) meta / npz files saved by the previous completion / grip generation steps

Output
------
1) model_with_gripper_oriented.stl
2) hole_orientation_info.npz
3) hole_orientation_info.json
4) hole_orientation_info.txt
5) optional transformed point clouds / extra STL files

Coordinate convention after transformation
------------------------------------------
- The whole model means: repair model + gripper in model_with_gripper.stl.
- The new origin is the center of the AABB bounding box of the whole rotated model.
- side_n, the inward normal of the selected side face, is aligned to +Y.
- top_n, the inward normal of the top plane, is aligned to +Z.
- Unit is unchanged. If your STL is in meter, the output STL is still in meter.

Important note
--------------
Requirement 2 says the new origin is the bounding-box center. Therefore this code
centers the whole model at the AABB center after rotation. In this convention the
"top plane贴着 XOY" is interpreted as: the top plane is parallel to XOY and its
inward normal is +Z. The top plane is not forcibly shifted to z=0, because that
would break the bounding-box-center origin requirement.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import numpy as np
import open3d as o3d


# ============================================================
# User config
# ============================================================
# 修改这里为你的 hole completion / hole grip 输出目录。
COMPLETION_DIR = r"E:\HKUSTGZ\AAM\construction\data\completion_result\hole"

# hole_grip.py 保存的带 gripper 的模型。
INPUT_STL_NAME = "model_with_gripper.stl"
OUTPUT_STL_NAME = "model_oriented.stl"

# 保存姿态标准化信息。
ORIENTATION_NPZ_NAME = "hole_orientation_info.npz"
ORIENTATION_JSON_NAME = "hole_orientation_info.json"
ORIENTATION_TXT_NAME = "hole_orientation_info.txt"
TRANSFORMED_META_NPZ_NAME = "hole_meta_oriented.npz"

# 如果 meta 里有多个 side_n_mark，例如 max_u_outward / max_v_outward，
# 而没有明确保存 selected_side_key / grip_side_key，那么需要你手动指定。
# 示例：SELECT_SIDE_KEY = "max_u_outward"
# 如果 hole_grip.py 已经保存了 side_n / side_n_axis / side_n_inward，则保持 None 即可。
SELECT_SIDE_KEY: Optional[str] = None

# 如果你知道 top_n 或 side_n 在 npz 里的确切 key，可以在这里指定；否则自动搜索。
TOP_N_KEY: Optional[str] = None
SIDE_N_KEY: Optional[str] = None

# 如果只找到 side_n_mark，且 key 名包含 outward，则会取负号转为 inward。
# 你的要求是 side_n = 指向模型内侧的法线，因此这里默认 True。
CONVERT_OUTWARD_SIDE_MARK_TO_INWARD = True

# 是否额外变换目录中的点云 / STL 辅助文件。
TRANSFORM_EXTRA_GEOMETRIES = True
EXTRA_GEOMETRY_NAMES = [
    "model.stl",
    "model_processed.stl",
    "repair_model.stl",
    "grip.stl",
    "top_plane.pcd",
    "side_plane.pcd",
    "u_side_plane.pcd",
    "v_side_plane.pcd",
    "model.pcd",
]

VISUALIZE = True

TARGET_SIDE_N = np.array([0.0, 1.0, 0.0], dtype=np.float64)  # +Y
TARGET_TOP_N = np.array([0.0, 0.0, 1.0], dtype=np.float64)   # +Z


# ============================================================
# Basic utils
# ============================================================
def normalize(v: np.ndarray, name: str = "vector") -> np.ndarray:
    v = np.asarray(v, dtype=np.float64).reshape(3)
    n = np.linalg.norm(v)
    if n < 1e-12:
        raise ValueError(f"{name} is zero-length: {v}")
    return v / n


def make_T(R: np.ndarray, t: np.ndarray) -> np.ndarray:
    T = np.eye(4, dtype=np.float64)
    T[:3, :3] = np.asarray(R, dtype=np.float64).reshape(3, 3)
    T[:3, 3] = np.asarray(t, dtype=np.float64).reshape(3)
    return T


def apply_T_to_points(points: np.ndarray, T: np.ndarray) -> np.ndarray:
    points = np.asarray(points, dtype=np.float64)
    if points.ndim == 1:
        return T[:3, :3] @ points.reshape(3) + T[:3, 3]
    return (T[:3, :3] @ points.T).T + T[:3, 3].reshape(1, 3)


def apply_R_to_vectors(vectors: np.ndarray, R: np.ndarray) -> np.ndarray:
    vectors = np.asarray(vectors, dtype=np.float64)
    if vectors.ndim == 1:
        return R @ vectors.reshape(3)
    return (R @ vectors.T).T


def unwrap_np_value(x: Any) -> Any:
    """Convert numpy scalar/object array to normal Python value when possible."""
    if isinstance(x, np.ndarray):
        if x.shape == ():
            return x.item()
    return x


def to_jsonable(x: Any) -> Any:
    if isinstance(x, np.ndarray):
        return x.tolist()
    if isinstance(x, (np.integer, np.floating)):
        return x.item()
    if isinstance(x, Path):
        return str(x)
    if isinstance(x, dict):
        return {str(k): to_jsonable(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [to_jsonable(v) for v in x]
    return x


# ============================================================
# Loading meta / normals
# ============================================================
def find_existing_file(candidates: Iterable[Path], what: str) -> Path:
    tried = []
    for p in candidates:
        p = Path(p)
        tried.append(str(p))
        if p.exists():
            return p
    raise FileNotFoundError(f"Cannot find {what}. Tried:\n" + "\n".join(tried))


def collect_npz_paths(completion_dir: Path, user_meta_path: Optional[str] = None) -> List[Path]:
    candidates: List[Path] = []
    if user_meta_path:
        candidates.append(Path(user_meta_path))

    common_names = [
        "hole_grip_info.npz",
        "grip_info.npz",
        "model_with_gripper_info.npz",
        "meta_with_gripper.npz",
        "meta.npz",
        "completion_meta.npz",
    ]
    candidates.extend([completion_dir / name for name in common_names])

    # 兼容之前代码中可能出现的 completion_dir + 'meta.npz' 少斜杠问题。
    candidates.append(Path(str(completion_dir) + "meta.npz"))

    # 最后扫描目录中所有 npz，按名字优先级排序。
    if completion_dir.exists():
        all_npz = sorted(completion_dir.glob("*.npz"))
        priority_words = ("grip", "with_gripper", "meta", "completion")
        all_npz = sorted(
            all_npz,
            key=lambda p: (
                0 if any(w in p.name.lower() for w in priority_words) else 1,
                p.name.lower(),
            ),
        )
        candidates.extend(all_npz)

    # 去重但保持顺序。
    seen = set()
    out = []
    for p in candidates:
        s = str(p)
        if s not in seen:
            seen.add(s)
            out.append(p)
    return out


def load_npz_files(completion_dir: Path, user_meta_path: Optional[str] = None) -> Tuple[Dict[str, Any], List[str]]:
    """
    Load all available npz metadata files and merge them.
    Later files do not overwrite earlier keys unless the earlier value is missing.
    """
    meta: Dict[str, Any] = {}
    loaded_paths: List[str] = []

    for p in collect_npz_paths(completion_dir, user_meta_path):
        if not p.exists():
            continue
        try:
            data = np.load(p, allow_pickle=True)
        except Exception as e:
            print(f"[warn] skip npz {p}: {e}")
            continue

        loaded_paths.append(str(p))
        for key in data.files:
            if key not in meta:
                meta[key] = unwrap_np_value(data[key])

    if not loaded_paths:
        raise FileNotFoundError(
            "No npz metadata found. Please make sure hole_grip.py saved one of: "
            "hole_grip_info.npz / grip_info.npz / model_with_gripper_info.npz / meta.npz"
        )

    return meta, loaded_paths


def get_array3_from_meta(meta: Dict[str, Any], keys: Iterable[str]) -> Tuple[Optional[np.ndarray], Optional[str]]:
    for key in keys:
        if key in meta:
            arr = np.asarray(meta[key], dtype=np.float64)
            if arr.shape == (3,):
                return arr, key
            if arr.size == 3:
                return arr.reshape(3), key
    return None, None


def find_top_n(meta: Dict[str, Any], explicit_key: Optional[str] = None) -> Tuple[np.ndarray, str]:
    if explicit_key:
        if explicit_key not in meta:
            raise KeyError(f"TOP_N_KEY={explicit_key!r} not found in meta keys: {list(meta.keys())}")
        return normalize(np.asarray(meta[explicit_key], dtype=np.float64), explicit_key), explicit_key

    candidate_keys = [
        "top_n",
        "top_n_axis",
        "top_normal",
        "top_normal_inward",
        "top_n_inward",
        "top_plane_n",
        "top_plane_normal",
        "n_axis",  # 你之前的补全代码里 n_axis 通常就是顶面 inward normal
    ]
    top_n, used_key = get_array3_from_meta(meta, candidate_keys)
    if top_n is not None:
        return normalize(top_n, used_key), used_key  # type: ignore[arg-type]

    # 兜底：从 top_plane_model = [a,b,c,d] 取法线。
    if "top_plane_model" in meta:
        plane = np.asarray(meta["top_plane_model"], dtype=np.float64).reshape(-1)
        if plane.size >= 3:
            return normalize(plane[:3], "top_plane_model[:3]"), "top_plane_model[:3]"

    raise KeyError(
        "Cannot find top_n. Please save top_n/top_n_axis/top_n_inward/n_axis "
        "in hole_grip.py metadata, or set TOP_N_KEY manually."
    )


def normalize_side_key_name(key: str) -> str:
    key = str(key)
    if key.endswith("_outward") or key.endswith("_inward"):
        return key
    # selected_side_key 可能保存为 max_u / min_v，需要补全 outward。
    if key in {"min_u", "max_u", "min_v", "max_v"}:
        return key + "_outward"
    return key


def find_selected_side_key(meta: Dict[str, Any], side_n_mark: Dict[str, Any]) -> Optional[str]:
    selected_key_candidates = [
        "selected_side_key",
        "grip_side_key",
        "attach_side_key",
        "side_key",
        "side_name",
        "selected_side_name",
        "grip_side_name",
        "attach_side_name",
    ]

    for k in selected_key_candidates:
        if k in meta:
            raw = unwrap_np_value(meta[k])
            if isinstance(raw, bytes):
                raw = raw.decode("utf-8")
            key = normalize_side_key_name(str(raw))
            if key in side_n_mark:
                return key

    return None


def load_side_n_mark(meta: Dict[str, Any]) -> Optional[Dict[str, np.ndarray]]:
    if "side_n_mark" not in meta:
        return None

    raw = unwrap_np_value(meta["side_n_mark"])
    if not isinstance(raw, dict):
        raise TypeError(f"side_n_mark should be dict, got {type(raw)}")

    out: Dict[str, np.ndarray] = {}
    for k, v in raw.items():
        out[str(k)] = normalize(np.asarray(v, dtype=np.float64), f"side_n_mark[{k}]")
    return out


def find_side_n(
    meta: Dict[str, Any],
    explicit_key: Optional[str] = None,
    selected_side_key: Optional[str] = None,
    convert_outward_to_inward: bool = True,
) -> Tuple[np.ndarray, str, str]:
    """
    Returns
    -------
    side_n_inward, used_key, source_type
    """
    if explicit_key:
        if explicit_key not in meta:
            raise KeyError(f"SIDE_N_KEY={explicit_key!r} not found in meta keys: {list(meta.keys())}")
        return normalize(np.asarray(meta[explicit_key], dtype=np.float64), explicit_key), explicit_key, "direct"

    direct_keys = [
        "side_n",
        "side_n_axis",
        "side_normal",
        "side_normal_inward",
        "side_n_inward",
        "selected_side_n",
        "selected_side_normal",
        "grip_side_n",
        "grip_side_normal",
        "attach_side_n",
        "attach_side_normal",
    ]
    side_n, used_key = get_array3_from_meta(meta, direct_keys)
    if side_n is not None:
        return normalize(side_n, used_key), used_key, "direct"  # type: ignore[arg-type]

    side_n_mark = load_side_n_mark(meta)
    if side_n_mark is None:
        raise KeyError(
            "Cannot find side_n. Please save side_n/side_n_axis/side_n_inward in hole_grip.py, "
            "or save side_n_mark plus selected_side_key/grip_side_key."
        )

    if selected_side_key is not None:
        key = normalize_side_key_name(selected_side_key)
        if key not in side_n_mark:
            raise KeyError(
                f"SELECT_SIDE_KEY={selected_side_key!r} not found in side_n_mark. "
                f"Available keys: {list(side_n_mark.keys())}"
            )
    else:
        key = find_selected_side_key(meta, side_n_mark)
        if key is None:
            if len(side_n_mark) == 1:
                key = next(iter(side_n_mark.keys()))
            else:
                raise KeyError(
                    "side_n_mark has multiple candidates, but no selected side key was found.\n"
                    f"Available side_n_mark keys: {list(side_n_mark.keys())}\n"
                    "Please either:\n"
                    "  1) save side_n / side_n_axis / side_n_inward directly in hole_grip.py, or\n"
                    "  2) save selected_side_key / grip_side_key, or\n"
                    "  3) set SELECT_SIDE_KEY at the top of this file."
                )

    side = normalize(side_n_mark[key], f"side_n_mark[{key}]")
    source_type = "side_n_mark"

    # side_n_mark 在你之前代码里通常保存的是 outward normal。
    # 当前要求是 inward normal，所以默认取负号。
    if convert_outward_to_inward and "outward" in key.lower():
        side = -side
        source_type = "side_n_mark_outward_converted_to_inward"
    elif "inward" in key.lower():
        source_type = "side_n_mark_inward"

    return normalize(side, "side_n_inward"), key, source_type


# ============================================================
# Rotation construction
# ============================================================
def rotation_align_side_top_to_yz(side_n_src: np.ndarray, top_n_src: np.ndarray) -> Tuple[np.ndarray, Dict[str, np.ndarray]]:
    """
    Build R so that:
        R @ side_n_src == +Y
        R @ top_n_src  == +Z

    The source basis is built as:
        z_src = top_n_src
        y_src = side_n_src projected onto the plane perpendicular to z_src
        x_src = y_src cross z_src

    This produces a right-handed source basis [x_src, y_src, z_src].
    """
    z_src = normalize(top_n_src, "top_n_src")
    y_raw = normalize(side_n_src, "side_n_src")

    y_src = y_raw - np.dot(y_raw, z_src) * z_src
    y_norm = np.linalg.norm(y_src)
    if y_norm < 1e-8:
        raise ValueError(
            "side_n_src and top_n_src are nearly parallel. "
            "A side normal should be perpendicular to top normal."
        )
    y_src = y_src / y_norm

    x_src = normalize(np.cross(y_src, z_src), "x_src = side x top")

    # Re-orthogonalize z to remove numeric drift and guarantee right-handed basis.
    z_src = normalize(np.cross(x_src, y_src), "z_src reorthogonalized")

    S = np.column_stack([x_src, y_src, z_src])
    Tgt = np.eye(3, dtype=np.float64)

    R = Tgt @ S.T

    # Numerical cleanup.
    U, _, Vt = np.linalg.svd(R)
    R = U @ Vt
    if np.linalg.det(R) < 0:
        U[:, -1] *= -1
        R = U @ Vt

    basis_info = {
        "x_src": x_src,
        "y_src": y_src,
        "z_src": z_src,
        "side_n_src_projected": y_src,
        "top_n_src_reorthogonalized": z_src,
        "side_n_dst_check": R @ y_raw,
        "top_n_dst_check": R @ normalize(top_n_src, "top_n_src_original"),
    }
    return R, basis_info


def compute_bbox(vertices: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    vertices = np.asarray(vertices, dtype=np.float64)
    bbox_min = vertices.min(axis=0)
    bbox_max = vertices.max(axis=0)
    bbox_center = 0.5 * (bbox_min + bbox_max)
    bbox_size = bbox_max - bbox_min
    return bbox_min, bbox_max, bbox_center, bbox_size


# ============================================================
# Plane / meta transformation helpers
# ============================================================
def transform_plane_model(plane: np.ndarray, R: np.ndarray, t: np.ndarray) -> np.ndarray:
    """
    Transform plane coefficients [a,b,c,d] under p' = R p + t.
    Original: n dot p + d = 0
    New:      n' dot p' + d' = 0
    n' = R n
    d' = d - n' dot t
    """
    plane = np.asarray(plane, dtype=np.float64).reshape(-1)
    if plane.size < 4:
        raise ValueError("plane model should be [a,b,c,d]")
    n = normalize(plane[:3], "plane normal")
    d = float(plane[3])
    n_new = normalize(R @ n, "transformed plane normal")
    d_new = d - float(np.dot(n_new, t))
    return np.array([n_new[0], n_new[1], n_new[2], d_new], dtype=np.float64)


def maybe_transform_meta_value(key: str, value: Any, R: np.ndarray, T: np.ndarray) -> Any:
    """
    Best-effort transformation for common metadata.

    - point / center / origin / vertex arrays are transformed by full T.
    - normal / axis / vector arrays are transformed by R only.
    - plane_model [a,b,c,d] is transformed as plane coefficients.
    - side_n_mark dict is transformed by R for each vector.
    """
    key_l = key.lower()
    value = unwrap_np_value(value)

    if isinstance(value, dict):
        out = {}
        for k, v in value.items():
            arr = np.asarray(v)
            if arr.size == 3:
                out[str(k)] = apply_R_to_vectors(arr.reshape(3), R)
            else:
                out[str(k)] = v
        return out

    try:
        arr = np.asarray(value)
    except Exception:
        return value

    # Keep strings / objects unchanged.
    if arr.dtype.kind in {"U", "S", "O"}:
        return value

    # Plane model.
    if "plane_model" in key_l or key_l.endswith("_plane"):
        if arr.size == 4:
            try:
                return transform_plane_model(arr.reshape(4), R, T[:3, 3])
            except Exception:
                return value

    # Single normal / axis / vector.
    vector_words = ["normal", "axis", "_n", "n_", "vec", "vector"]
    point_words = ["point", "center", "origin", "vertex", "vertices", "corner", "attach", "base"]

    if arr.shape == (3,) or arr.size == 3:
        arr3 = arr.reshape(3).astype(np.float64)
        if any(w in key_l for w in vector_words) and not any(w in key_l for w in point_words):
            return apply_R_to_vectors(arr3, R)
        if any(w in key_l for w in point_words):
            return apply_T_to_points(arr3, T)
        return value

    # Nx3 point arrays.
    if arr.ndim == 2 and arr.shape[1] == 3:
        if any(w in key_l for w in point_words) or "pcd" in key_l or "points" in key_l:
            return apply_T_to_points(arr.astype(np.float64), T)
        if any(w in key_l for w in vector_words):
            return apply_R_to_vectors(arr.astype(np.float64), R)

    return value


def save_transformed_meta(meta: Dict[str, Any], R: np.ndarray, T: np.ndarray, output_path: Path) -> None:
    transformed: Dict[str, Any] = {}
    for key, value in meta.items():
        transformed[key] = maybe_transform_meta_value(key, value, R, T)

    # np.savez can store dict as object arrays. Use allow_pickle=True when reading.
    np.savez(output_path, **transformed)
    print(f"[saved] transformed meta: {output_path}")


# ============================================================
# Geometry IO
# ============================================================
def read_mesh_vertices(mesh_path: Path) -> Tuple[o3d.geometry.TriangleMesh, np.ndarray]:
    mesh = o3d.io.read_triangle_mesh(str(mesh_path))
    if len(mesh.vertices) == 0:
        raise RuntimeError(f"Empty STL mesh: {mesh_path}")
    vertices = np.asarray(mesh.vertices, dtype=np.float64)
    return mesh, vertices


def transform_mesh_file(input_path: Path, output_path: Path, T: np.ndarray) -> None:
    mesh = o3d.io.read_triangle_mesh(str(input_path))
    if len(mesh.vertices) == 0:
        print(f"[warn] skip empty mesh: {input_path}")
        return
    vertices = np.asarray(mesh.vertices, dtype=np.float64)
    vertices_out = apply_T_to_points(vertices, T)
    mesh.vertices = o3d.utility.Vector3dVector(vertices_out)
    mesh.compute_vertex_normals()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    ok = o3d.io.write_triangle_mesh(str(output_path), mesh, write_ascii=False)
    if not ok:
        raise RuntimeError(f"Failed to write mesh: {output_path}")
    print(f"[saved] transformed mesh: {output_path}")


def transform_pcd_file(input_path: Path, output_path: Path, T: np.ndarray) -> None:
    pcd = o3d.io.read_point_cloud(str(input_path))
    if len(pcd.points) == 0:
        print(f"[warn] skip empty point cloud: {input_path}")
        return
    points = np.asarray(pcd.points, dtype=np.float64)
    pcd.points = o3d.utility.Vector3dVector(apply_T_to_points(points, T))

    # Normals are vectors, so only rotate them.
    if pcd.has_normals():
        normals = np.asarray(pcd.normals, dtype=np.float64)
        pcd.normals = o3d.utility.Vector3dVector(apply_R_to_vectors(normals, T[:3, :3]))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    ok = o3d.io.write_point_cloud(str(output_path), pcd)
    if not ok:
        raise RuntimeError(f"Failed to write point cloud: {output_path}")
    print(f"[saved] transformed point cloud: {output_path}")


def oriented_extra_name(path: Path) -> str:
    return path.stem + "_oriented" + path.suffix


def transform_extra_geometries(completion_dir: Path, input_main_stl: Path, T: np.ndarray) -> List[str]:
    saved: List[str] = []
    if not TRANSFORM_EXTRA_GEOMETRIES:
        return saved

    for name in EXTRA_GEOMETRY_NAMES:
        p = completion_dir / name
        if not p.exists():
            continue
        if p.resolve() == input_main_stl.resolve():
            continue

        out = completion_dir / oriented_extra_name(p)
        suffix = p.suffix.lower()
        try:
            if suffix == ".stl":
                transform_mesh_file(p, out, T)
                saved.append(str(out))
            elif suffix in {".pcd", ".ply", ".xyz", ".xyzn", ".xyzrgb"}:
                transform_pcd_file(p, out, T)
                saved.append(str(out))
        except Exception as e:
            print(f"[warn] failed to transform {p}: {e}")

    return saved


# ============================================================
# Main orientation API
# ============================================================
def orient_hole_model(
    completion_dir: str = COMPLETION_DIR,
    input_stl_path: Optional[str] = None,
    output_stl_path: Optional[str] = None,
    meta_path: Optional[str] = None,
    top_n_key: Optional[str] = TOP_N_KEY,
    side_n_key: Optional[str] = SIDE_N_KEY,
    selected_side_key: Optional[str] = SELECT_SIDE_KEY,
    visualize: bool = VISUALIZE,
) -> Dict[str, Any]:
    completion_dir_p = Path(completion_dir)

    input_stl = Path(input_stl_path) if input_stl_path else completion_dir_p / INPUT_STL_NAME
    output_stl = Path(output_stl_path) if output_stl_path else completion_dir_p / OUTPUT_STL_NAME

    if not input_stl.exists():
        raise FileNotFoundError(f"Cannot find input STL: {input_stl}")

    meta, loaded_meta_paths = load_npz_files(completion_dir_p, meta_path)

    top_n_src, top_n_used_key = find_top_n(meta, explicit_key=top_n_key)
    side_n_src, side_n_used_key, side_source_type = find_side_n(
        meta,
        explicit_key=side_n_key,
        selected_side_key=selected_side_key,
        convert_outward_to_inward=CONVERT_OUTWARD_SIDE_MARK_TO_INWARD,
    )

    # Construct rotation.
    R, basis_info = rotation_align_side_top_to_yz(side_n_src, top_n_src)

    # Read whole model with gripper and rotate first.
    mesh, vertices = read_mesh_vertices(input_stl)
    vertices_rot = (R @ vertices.T).T

    bbox_min_before, bbox_max_before, bbox_center_before, bbox_size_before = compute_bbox(vertices)
    bbox_min_rot, bbox_max_rot, bbox_center_rot, bbox_size_rot = compute_bbox(vertices_rot)

    # New origin = AABB center of the whole rotated model.
    t = -bbox_center_rot
    T = make_T(R, t)

    vertices_out = vertices_rot + t.reshape(1, 3)
    bbox_min_after, bbox_max_after, bbox_center_after, bbox_size_after = compute_bbox(vertices_out)

    mesh.vertices = o3d.utility.Vector3dVector(vertices_out)
    mesh.compute_vertex_normals()

    output_stl.parent.mkdir(parents=True, exist_ok=True)
    ok = o3d.io.write_triangle_mesh(str(output_stl), mesh, write_ascii=False)
    if not ok:
        raise RuntimeError(f"Failed to write oriented STL: {output_stl}")

    top_n_after = normalize(R @ top_n_src, "top_n_after")
    side_n_after = normalize(R @ side_n_src, "side_n_after")

    # Transform optional extra geometry.
    extra_saved = transform_extra_geometries(completion_dir_p, input_stl, T)

    # Save transformed metadata.
    transformed_meta_path = completion_dir_p / TRANSFORMED_META_NPZ_NAME
    try:
        save_transformed_meta(meta, R, T, transformed_meta_path)
    except Exception as e:
        print(f"[warn] failed to save transformed meta: {e}")
        transformed_meta_path = None  # type: ignore[assignment]

    orientation_info: Dict[str, Any] = {
        "completion_dir": str(completion_dir_p),
        "input_stl": str(input_stl),
        "output_stl": str(output_stl),
        "loaded_meta_paths": loaded_meta_paths,
        "top_n_used_key": top_n_used_key,
        "side_n_used_key": side_n_used_key,
        "side_source_type": side_source_type,
        "selected_side_key_config": selected_side_key,
        "unit_scale": 1.0,
        "unit_note": "No unit conversion is applied. Input meter -> output meter.",
        "target_side_n": TARGET_SIDE_N,
        "target_top_n": TARGET_TOP_N,
        "top_n_src": top_n_src,
        "side_n_src_inward": side_n_src,
        "top_n_after": top_n_after,
        "side_n_after": side_n_after,
        "R": R,
        "t": t,
        "T": T,
        "bbox_min_before": bbox_min_before,
        "bbox_max_before": bbox_max_before,
        "bbox_center_before": bbox_center_before,
        "bbox_size_before": bbox_size_before,
        "bbox_min_rot_before_centering": bbox_min_rot,
        "bbox_max_rot_before_centering": bbox_max_rot,
        "bbox_center_rot_before_centering": bbox_center_rot,
        "bbox_size_rot_before_centering": bbox_size_rot,
        "bbox_min_after": bbox_min_after,
        "bbox_max_after": bbox_max_after,
        "bbox_center_after": bbox_center_after,
        "bbox_size_after": bbox_size_after,
        "basis_info": basis_info,
        "extra_saved": extra_saved,
        "transformed_meta_path": str(transformed_meta_path) if transformed_meta_path else None,
    }

    # Save NPZ.
    npz_path = completion_dir_p / ORIENTATION_NPZ_NAME
    np.savez(
        npz_path,
        T=T,
        R=R,
        t=t,
        top_n_src=top_n_src,
        side_n_src_inward=side_n_src,
        top_n_after=top_n_after,
        side_n_after=side_n_after,
        target_top_n=TARGET_TOP_N,
        target_side_n=TARGET_SIDE_N,
        bbox_min_before=bbox_min_before,
        bbox_max_before=bbox_max_before,
        bbox_center_before=bbox_center_before,
        bbox_size_before=bbox_size_before,
        bbox_min_after=bbox_min_after,
        bbox_max_after=bbox_max_after,
        bbox_center_after=bbox_center_after,
        bbox_size_after=bbox_size_after,
        top_n_used_key=np.array(top_n_used_key),
        side_n_used_key=np.array(side_n_used_key),
        side_source_type=np.array(side_source_type),
        input_stl=np.array(str(input_stl)),
        output_stl=np.array(str(output_stl)),
        loaded_meta_paths=np.array(loaded_meta_paths, dtype=object),
    )

    # Save JSON.
    json_path = completion_dir_p / ORIENTATION_JSON_NAME
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(to_jsonable(orientation_info), f, ensure_ascii=False, indent=2)

    # Save TXT summary.
    txt_path = completion_dir_p / ORIENTATION_TXT_NAME
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write("hole_orientation.py result\n")
        f.write("==========================\n\n")
        f.write(f"input_stl  = {input_stl}\n")
        f.write(f"output_stl = {output_stl}\n")
        f.write(f"npz        = {npz_path}\n")
        f.write(f"json       = {json_path}\n")
        f.write(f"meta used  = {loaded_meta_paths}\n\n")
        f.write(f"top_n_used_key  = {top_n_used_key}\n")
        f.write(f"side_n_used_key = {side_n_used_key}\n")
        f.write(f"side_source_type = {side_source_type}\n\n")
        f.write("R =\n")
        f.write(np.array2string(R, precision=12, suppress_small=False))
        f.write("\n\nt =\n")
        f.write(np.array2string(t, precision=12, suppress_small=False))
        f.write("\n\nT =\n")
        f.write(np.array2string(T, precision=12, suppress_small=False))
        f.write("\n\ncheck normals:\n")
        f.write(f"R @ top_n_src  = {top_n_after}\n")
        f.write(f"R @ side_n_src = {side_n_after}\n")
        f.write("\ncheck bbox after orientation:\n")
        f.write(f"bbox_min_after    = {bbox_min_after}\n")
        f.write(f"bbox_max_after    = {bbox_max_after}\n")
        f.write(f"bbox_center_after = {bbox_center_after}\n")
        f.write(f"bbox_size_after   = {bbox_size_after}\n")

    print("\n========== hole orientation finished ==========")
    print(f"[saved] oriented STL: {output_stl}")
    print(f"[saved] T/R/t npz:    {npz_path}")
    print(f"[saved] json:         {json_path}")
    print(f"[saved] txt:          {txt_path}")
    print(f"top_n source key:     {top_n_used_key}")
    print(f"side_n source key:    {side_n_used_key}")
    print(f"side source type:     {side_source_type}")
    print(f"R @ top_n_src:        {top_n_after}")
    print(f"R @ side_n_src:       {side_n_after}")
    print(f"bbox center after:    {bbox_center_after}")
    print("Unit: unchanged, no meter/mm conversion applied.")
    print("==============================================\n")

    if visualize:
        frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=max(float(bbox_size_after.max()), 1e-3) * 0.25)
        o3d.visualization.draw_geometries([mesh, frame])

    return orientation_info


# ============================================================
# CLI
# ============================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Orient hole model_with_gripper.stl to standardized frame.")
    parser.add_argument("--completion-dir", default=COMPLETION_DIR, help="Directory containing model_with_gripper.stl and meta npz files.")
    parser.add_argument("--input-stl", default=None, help="Input STL path. Default: completion_dir/model_with_gripper.stl")
    parser.add_argument("--output-stl", default=None, help="Output STL path. Default: completion_dir/model_with_gripper_oriented.stl")
    parser.add_argument("--meta", default=None, help="Optional explicit metadata npz path.")
    parser.add_argument("--top-n-key", default=TOP_N_KEY, help="Explicit top inward normal key in npz.")
    parser.add_argument("--side-n-key", default=SIDE_N_KEY, help="Explicit side inward normal key in npz.")
    parser.add_argument("--selected-side-key", default=SELECT_SIDE_KEY, help="Key in side_n_mark, e.g. max_u_outward / max_v_outward.")
    parser.add_argument("--visualize", action="store_true", help="Visualize oriented mesh and coordinate frame.")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    orient_hole_model(
        completion_dir=args.completion_dir,
        input_stl_path=args.input_stl,
        output_stl_path=args.output_stl,
        meta_path=args.meta,
        top_n_key=args.top_n_key,
        side_n_key=args.side_n_key,
        selected_side_key=args.selected_side_key,
        visualize=args.visualize,
    )
